import { createContext, useContext, useEffect, useMemo, useState } from "react";

const LanguageContext = createContext(null);

export const translations = {
  vi: {
    nav: {
      home: "Trang chủ",
      about: "Giới thiệu",
      offers: "Ưu đãi",
      transfer: "Chuyển tiền",
      contact: "Liên hệ",
      login: "Đăng nhập",
      dashboard: "Dashboard",
      logout: "Đăng xuất",
      profile: "Hồ sơ cá nhân",
      qrDeposit: "Nạp QR Sandbox",
      myQr: "QR Nhận tiền",
      myWallets: "Ví của tôi",
      investment: "Tích lũy & Đầu tư",
      support: "Hỗ trợ trực tuyến",
      savingsVaults: "Ví tiết kiệm",
    },
    index: {
      eyebrow: "SmartWallet Tài chính số",
      heroTitle1: "Xây dựng trải nghiệm",
      heroTitle2: "SmartWallet",
      heroTitle3: "mượt mà cho người dùng hiện đại.",
      heroLead:
        "Quản lý số dư thời gian thực, nạp/rút tiền nhanh chóng, theo dõi chi tiêu qua biểu đồ trực quan và tạo hũ tiết kiệm theo mục tiêu cá nhân.",
      getStarted: "Bắt đầu ngay →",
      ourServices: "Dịch vụ",
      serviceTitle: "Dịch vụ tài chính nổi bật của SmartWallet",
      offerPrefix: "Ưu đãi #",
      offersCount: "ưu đãi",
      offerRunning: "Ưu đãi đang chạy",
      newsEyebrow: "SmartWallet Insights",
      newsTitle: "Tin tức tài chính mới nhất",
      newsDesc:
        "Cập nhật nhanh các thông báo, ưu đãi và xu hướng tài chính số do admin SmartWallet đăng tải.",
      viewAll: "Xem tất cả",
      marketUpdate: "Cập nhật thị trường",
      readPost: "Đọc bài viết",
      finance: "Tài chính",
      justNow: "Vừa xong",
      newText: "Mới",
      featureTitle: "Dịch vụ cao cấp với trải nghiệm mượt mà.",
      closeNews: "Đóng chi tiết tin tức",
      savingsTitle: "Ví Tích Lũy Thông Minh (Savings Vault)",
      savingsSubtitle: "Sinh lời vượt trội, tích lũy tự động cho tương lai tự do tài chính",
      savingsInterestRate: "Lãi suất ưu đãi lên tới 8.5%/năm",
      savingsDesc: "SmartWallet mang đến giải pháp tích lũy tối ưu. Bạn có thể chia nhỏ nguồn tiền thành nhiều hũ tiết kiệm thông minh theo từng mục tiêu riêng biệt, theo dõi tiến trình trực quan và tận hưởng sức mạnh lãi kép.",
      savingsButton: "Bắt đầu tích lũy ngay",
      savingsFeature1Title: "Lãi suất tích lũy cao",
      savingsFeature1Desc: "Hưởng lãi suất hấp dẫn 8.5%/năm, nhận lãi hàng ngày, giúp dòng tiền của bạn luôn sinh sôi.",
      savingsFeature2Title: "Tự động gửi tích lũy",
      savingsFeature2Desc: "Thiết lập quy tắc tự động trích tiền lẻ hoặc gửi tiền định kỳ vào các hũ mục tiêu của bạn.",
      savingsFeature3Title: "Rút tiền linh hoạt",
      savingsFeature3Desc: "Không giới hạn thời gian rút tiền. Bạn có thể rút tiền về ví chính bất cứ lúc nào không lo mất lãi.",
    },
    cards: [
      {
        title: "💳 Nạp tiền",
        desc: "Nạp tiền nhanh chóng từ ngân hàng vào ví.",
      },
      {
        title: "💸 Chuyển tiền",
        desc: "Chuyển tiền an toàn và tức thì.",
      },
      {
        title: "🎁 Ưu đãi & Voucher",
        desc: "Ưu đãi độc quyền dành cho người dùng SmartWallet.",
      },
      {
        title: "📈 Đầu tư",
        desc: "Đầu tư thông minh với các gói tài chính linh hoạt.",
      },
    ],
    offers: [
      {
        title: "Giảm 20% phí giao dịch",
        description: "Áp dụng cho chuyển tiền và thanh toán QR.",
      },
      {
        title: "Voucher nạp ví",
        description: "Nhận ưu đãi khi nạp ví lần đầu.",
      },
      {
        title: "Hoàn tiền QR",
        description: "Hoàn tiền khi thanh toán QR tại cửa hàng.",
      },
    ],
    news: [
      {
        title: "SmartWallet cập nhật bảo mật giao dịch thời gian thực",
        tag: "Tài chính số",
        time: "Vừa xong",
        content:
          "Theo dõi biến động số dư, cảnh báo giao dịch và bảo vệ ví điện tử với trải nghiệm nhanh, rõ ràng hơn cho người dùng SmartWallet.",
      },
      {
        title: "Ưu đãi phí chuyển tiền cho người dùng mới",
        tag: "Ưu đãi",
        time: "Hôm nay",
        content:
          "Các chương trình voucher mới giúp người dùng tiết kiệm chi phí khi chuyển tiền, nạp ví và thanh toán QR.",
      },
      {
        title: "Quản lý chi tiêu cá nhân bằng biểu đồ thông minh",
        tag: "Quản lý tiền",
        time: "1 ngày trước",
        content:
          "SmartWallet giúp phân loại dòng tiền, thống kê thu chi và hỗ trợ người dùng đưa ra quyết định tài chính tốt hơn.",
      },
    ],
    features: [
      {
        title: "Bảo mật tài khoản",
        desc: "Bảo vệ ví bằng KYC, PIN giao dịch và cảnh báo tức thì.",
      },
      {
        title: "Thanh toán linh hoạt",
        desc: "Nạp, rút, chuyển tiền và thanh toán ngân hàng trong cùng một hệ sinh thái.",
      },
      {
        title: "Quản lý tài chính",
        desc: "Theo dõi thu chi, ưu đãi và biến động số dư rõ ràng hơn.",
      },
    ],
    dashboard: {
      availableBalance: "Số dư khả dụng",
      active: "ĐANG HOẠT ĐỘNG",
      frozen: "BỊ ĐÓNG BĂNG",
      deposit: "Nạp tiền",
      withdraw: "Rút tiền",
      transfer: "Chuyển tiền",
      qrCode: "Mã QR",
      linkedBanks: "Ngân hàng liên kết",
      accountsLinked: "tài khoản đã liên kết",
      addBank: "Thêm ngân hàng",
      transactionHistory: "Lịch sử giao dịch",
      searchTransactions: "Tìm kiếm giao dịch...",
      all: "Tất cả",
      receive: "Nhận tiền",
      send: "Chuyển tiền",
      success: "Thành công",
      pending: "Đang xử lý",
      failed: "Thất bại",
      noTransactions: "Không tìm thấy giao dịch nào",
    },
    wallets: {
      freezeConfirmTitle: "Đóng băng ví của bạn?",
      freezeConfirmText: "Hành động này không thể tự hoàn tác. Đóng băng ví sẽ ngay lập tức vô hiệu hóa tất cả nạp, rút và chuyển tiền. Chỉ có đội ngũ hỗ trợ mới có thể mở khóa ví cho bạn.",
      freezeButton: "Đóng băng ngay",
      cancel: "Hủy",
      walletFrozenBanner: "Ví đã bị đóng băng. Tất cả giao dịch đã bị vô hiệu hóa. Vui lòng liên hệ hỗ trợ để phục hồi quyền truy cập.",
      contactSupport: "Liên hệ Hỗ trợ",
      pinSetupTitle: "Thiết lập mã PIN giao dịch",
      pinSetupText: "Vui lòng chọn mã PIN gồm 4 chữ số để sử dụng khi chuyển tiền hoặc rút tiền.",
      enterNewPin: "Nhập mã PIN mới (4 số)",
      confirmNewPin: "Xác nhận mã PIN mới",
      confirmAndSet: "Xác nhận & Thiết lập",
      enterPinToConfirm: "Nhập mã PIN giao dịch để xác nhận",
      depositTitle: "Nạp tiền vào ví",
      depositSuccess: "Nạp tiền thành công! Số dư của bạn đã được cập nhật.",
      minimumDeposit: "Số tiền nạp tối thiểu là 1.000₫!",
      selectLinkedBank: "Chọn tài khoản ngân hàng đã liên kết:",
      amountToDeposit: "Số tiền muốn nạp:",
      note: "Lời nhắn:",
      depositViaBank: "Nạp qua Ngân hàng liên kết",
      depositViaPayos: "Nạp qua QR Ngân hàng (PayOS)",
      processing: "Đang xử lý...",
      withdrawTitle: "Rút tiền về ngân hàng",
      withdrawMin: "Số tiền rút tối thiểu là 10.000₫!",
      selectBankWithdraw: "Chọn tài khoản ngân hàng nhận tiền:",
      transferTitle: "Chuyển tiền",
      transferMethod: "Phương thức chuyển tiền:",
      viaEmailPhone: "Qua Email / Số điện thoại",
      viaBankSandbox: "Qua Ngân hàng Sandbox",
      recipientEmail: "Email/SĐT người nhận:",
      amountToTransfer: "Số tiền chuyển:",
      selectCategory: "Chọn danh mục chuyển tiền:",
      applyVoucher: "Áp dụng mã giảm giá:",
      placeholderVoucher: "Nhập mã voucher...",
      apply: "Áp dụng",
      appliedVoucher: "Đã áp dụng mã",
      saveText: "tiết kiệm được",
      chooseVoucher: "Chọn Voucher có sẵn",
      linkedBanksList: "Danh sách ngân hàng đã liên kết",
      unlink: "Hủy liên kết",
      bankName: "Tên ngân hàng",
      accountNumber: "Số tài khoản",
      accountHolder: "Tên chủ tài khoản",
      linkNewBank: "Liên kết ngân hàng mới",
      selectBank: "Chọn ngân hàng",
      submit: "Xác nhận",
      depositDesc: "Nạp tiền vào tài khoản SmartWallet của bạn",
      selectDepositMethod: "Chọn phương thức nạp tiền",
      depositFromLinkedBankTitle: "🏦 Nạp tiền từ Ngân hàng liên kết",
      noLinkedBanksDesc: "Vui lòng liên kết tài khoản ngân hàng để thực hiện nạp tiền",
      linkBankNow: "Liên kết ngân hàng ngay",
      confirmDeposit: "Xác nhận nạp tiền",
      bankTransferDepositTitle: "📱 Nạp tiền chuyển khoản ngân hàng",
      bankTransferDepositDesc: "Vui lòng quét mã QR hoặc chuyển khoản thủ công tới tài khoản quản trị viên bên dưới",
      checkingStatus: "Hệ thống đang tự động kiểm tra trạng thái giao dịch...",
      openPayosPage: "🔗 Mở trang thanh toán PayOS (Chế độ thử nghiệm)",
      iHaveTransferred: "Tôi đã chuyển tiền",
      withdrawDesc: "Rút tiền về tài khoản ngân hàng của bạn",
      withdrawAmountLabel: "Số tiền rút (₫)",
      confirmWithdrawBtn: "Xác nhận rút tiền",
      withdrawPinDesc: "Vui lòng nhập mã PIN giao dịch gồm 4 chữ số để xác nhận rút tiền.",
      confirmWithdrawalTitle: "Xác nhận rút tiền",
      transferDesc: "Chuyển tiền nhanh chóng và an toàn",
      uploadQrTitle: "Tải lên ảnh mã QR ngân hàng (tùy chọn)",
      clickToUploadQr: "Nhấp để tải lên ảnh QR",
      orEnterManually: "hoặc nhập thủ công",
      recipientAccount: "Số tài khoản người nhận *",
      recipientOwner: "Tên chủ tài khoản (tùy chọn)",
      enterAccountPlaceholder: "Nhập số tài khoản",
      enterOwnerPlaceholder: "Tên đầy đủ người nhận",
      promoRewardTitle: "Mã giảm giá & Phần thưởng",
      browsePromoCodes: "Xem các mã giảm giá có sẵn",
      removePromo: "Gỡ bỏ",
      appliedPromo: "Đã áp dụng",
      discountPromo: "Giảm giá",
      enterVoucherAmountAlert: "Vui lòng nhập số tiền giao dịch để áp dụng mã giảm giá!",
      confirmTransferBtn: "Xác nhận chuyển tiền",
      confirmTransferDiscountedBtn: "Xác nhận chuyển tiền (Đã giảm giá)",
      selectPromoTitle: "Chọn mã giảm giá",
      minTxnAmount: "Giao dịch tối thiểu",
      expDate: "HSD",
      linkLimitReachedTitle: "Đã đạt giới hạn liên kết",
      linkLimitReachedDesc: "Bạn đã liên kết tối đa 3 ngân hàng. Vui lòng hủy liên kết một ngân hàng trước khi thêm mới.",
      linkedBanksProgress: "Ngân hàng đã liên kết",
      onlyOneSlotRemaining: "⚠️ Chỉ còn lại 1 lượt liên kết!",
      bankAccountsLinkedToWallet: "Tài khoản ngân hàng đã liên kết với ví của bạn:",
      addNewBankLink: "+ Thêm liên kết ngân hàng mới",
      txDetailTitle: "Chi tiết giao dịch",
      txDetailAmount: "Số tiền",
      txDetailId: "Mã giao dịch",
      txDetailType: "Loại giao dịch",
      txDetailCategory: "Danh mục",
      txDetailSender: "Người gửi",
      txDetailRecipient: "Người nhận",
      txDetailDate: "Ngày & Giờ",
      txDetailNote: "Lời nhắn",
      serviceFee: "Phí dịch vụ",
      noFee: "Miễn phí",
      feePerTxnHint: "Phí sẽ được cộng vào tổng khi bạn nhập số tiền",
      totalDeduction: "Tổng trừ từ ví",
      txDetailFee: "Phí giao dịch",
      txDetailTotal: "Tổng thanh toán",
      discount: "Giảm giá",
      cannotBeUndone: "Hành động này không thể tự hoàn tác",
      depositAmount: "Số tiền nạp",
      noLinkedBanks: "Chưa liên kết ngân hàng",
      bankNameLabel: "Ngân hàng",
      accountNumberLabel: "Số tài khoản",
      accountHolderLabel: "Chủ tài khoản",
      amountLabel: "Số tiền",
      transferNoteLabel: "Nội dung chuyển khoản",
      copyBtn: "Sao chép",
      copiedToast: "Đã sao chép",
      enterPinTransferDesc: "Vui lòng nhập mã PIN giao dịch gồm 4 chữ số để xác nhận chuyển tiền.",
      smartwalletTransferInfo: "Chuyển tiền trực tiếp đến tài khoản SmartWallet khác bằng số điện thoại hoặc email đã đăng ký.",
      bankTransferInfo: "Tải lên ảnh mã QR ngân hàng hoặc nhập thủ công thông tin tài khoản người nhận.",
      changeImage: "Thay đổi ảnh",
      banksCountLabel: "ngân hàng",
      removeBtn: "Gỡ",
      linkedCountLabel: "đã liên kết",
      noLinkedBanksDescWithdraw: "Vui lòng thêm tài khoản ngân hàng để thực hiện nạp/rút tiền dễ dàng.",
      kycVerifiedStatus: "Đã xác thực danh tính ✓",
      kycPendingStatus: "Đang chờ duyệt KYC ⏳",
      kycUnverifiedStatus: "Chưa xác thực danh tính ⚠️",
      scanningQr: "Đang quét mã QR...",
      qrTransferPayment: "Chuyển tiền qua mã QR",
      qrScanSuccess: "Quét QR thành công! Đã điền thông tin người nhận.",
      depositViaBankDesc: "Nạp tiền tức thì từ ngân hàng liên kết của bạn",
      depositViaPayosDesc: "Tạo mã QR động cho số tiền cần nạp",
      mbBankAdmin: "Ngân hàng Quân đội MB",
      bankLabel: "Ngân hàng",
      enterPhoneEmailPlaceholder: "Nhập số điện thoại hoặc email",
    },
    kyc: {
      title: "Xác thực danh tính (KYC)",
      subtitle: "Xác thực danh tính để nâng hạn mức giao dịch và mở khóa tất cả tính năng.",
      verifiedTitle: "Danh tính đã được xác thực",
      verifiedDesc: "Hạn mức giao dịch của bạn đã được nâng lên mức tối đa.",
      verifiedInfo: "Thông tin cá nhân đã xác thực",
      fullName: "Họ và tên",
      nationalId: "Số CCCD/CMND",
      dob: "Ngày sinh",
      gender: "Giới tính",
      address: "Địa chỉ thường trú",
      documentsTitle: "Giấy tờ tùy thân & Ảnh chân dung",
      idFront: "Mặt trước CCCD",
      idBack: "Mặt sau CCCD",
      selfie: "Ảnh selfie chân dung",
      noImage: "Chưa có ảnh",
      requestUpdate: "Yêu cầu cập nhật thông tin KYC",
      underReviewTitle: "Hồ sơ đang được xem xét",
      underReviewDesc: "Chúng tôi đã nhận được hồ sơ xác thực của bạn và đang tiến hành kiểm tra. Vui lòng chờ phản hồi trong vòng 1-3 ngày làm việc.",
      rejectedTitle: "Hồ sơ xác thực bị từ chối",
      rejectedDesc: "Vui lòng kiểm tra lại thông tin và ảnh tải lên để gửi lại hồ sơ.",
      personalInfo: "Thông tin cá nhân",
      uploadDocuments: "Tải lên giấy tờ",
      underReviewStep: "Đang xem xét",
      next: "Tiếp tục",
      back: "Quay lại",
      submitKyc: "Gửi hồ sơ xác thực",
      uploadPrompt: "Chọn ảnh",
      alertNote: "Ảnh chụp cần rõ nét, không bị mờ hoặc bị che khuất. Định dạng chấp nhận: JPG / PNG / WEBP / GIF, tối đa 5 MB.",
    },
    myQr: {
      title: "Mã QR nhận tiền của bạn",
      subtitle: "Dùng mã QR này để người khác quét và chuyển tiền vào ví SmartWallet của bạn.",
      userId: "Mã người dùng",
      email: "Email nhận",
      downloadQr: "Tải ảnh QR",
      copyQr: "Copy QR",
      copied: "Đã copy",
      transfer: "Chuyển tiền",
    },
    qrSandbox: {
      title: "SmartWallet Sandbox QR nạp tiền",
      subtitle: "Tạo mã QR giả lập để nạp tiền từ ngân hàng vào ví SmartWallet.",
      createTitle: "Tạo QR nạp tiền",
      amountLabel: "Số tiền nạp",
      amountPlaceholder: "VD: 100000",
      createBtn: "Tạo mã QR",
      creating: "Đang tạo QR...",
      demoFlowTitle: "Quy trình Demo Sandbox:",
      step1: "1. Nhập số tiền nạp.",
      step2: "2. Nhấp xác nhận giả lập quét QR để chuyển tiền từ ngân hàng vào ví.",
      paymentTitle: "Thanh toán QR",
      noQrText: "Chưa có QR. Hãy nhập số tiền và tạo QR.",
      amount: "Số tiền",
      reference: "Mã tham chiếu",
      status: "Trạng thái",
      simulateScanBtn: "Giả lập đã quét QR và thanh toán",
      simulating: "Đang giả lập thanh toán...",
      successTitle: "Nạp tiền thành công",
      failedTitle: "Giao dịch thất bại",
      newBalance: "Số dư mới",
    },
    notifications: {
      title: "Thông báo của bạn",
      subtitle: "Xem và quản lý tất cả các thông báo bảo mật và giao dịch.",
      empty: "Không có thông báo nào.",
      markAllRead: "Đánh dấu tất cả đã đọc",
      read: "Đã đọc",
      unread: "Chưa đọc",
      time: "Thời gian",
      viewAll: "Xem tất cả thông báo",
    },
    login: {
      title: "Đăng nhập SmartWallet",
      desc: "Nhập email và mật khẩu của bạn để truy cập dashboard ví điện tử.",
      emailLabel: "Địa chỉ Email",
      passLabel: "Mật khẩu",
      forgotPass: "Quên mật khẩu?",
      loginBtn: "Đăng nhập",
      loggingIn: "Đang đăng nhập...",
      needAccount: "Chưa có tài khoản?",
      registerNow: "Đăng ký ngay",
      registerTitle: "Đăng ký tài khoản",
      registerDesc: "Tạo tài khoản SmartWallet mới để bắt đầu quản lý tài chính.",
      phoneLabel: "Số điện thoại",
      confirmPassLabel: "Xác nhận mật khẩu",
      registerBtn: "Đăng ký",
      registering: "Đang đăng ký...",
      haveAccount: "Đã có tài khoản?",
      loginNow: "Đăng nhập ngay",
      forgotModalTitle: "Khôi phục mật khẩu",
      forgotModalDesc: "Nhập địa chỉ email của bạn để nhận mã OTP khôi phục.",
      sendOtp: "Gửi mã OTP",
      sending: "Đang gửi...",
      backToLogin: "Quay lại đăng nhập",
      enterOtpDesc: "Nhập mã OTP 6 chữ số đã được gửi tới email của bạn.",
      resetPassTitle: "Đặt lại mật khẩu mới",
      resetPassDesc: "Nhập mật khẩu mới cho tài khoản của bạn.",
      newPassLabel: "Mật khẩu mới",
      resetBtn: "Đặt lại mật khẩu",
      resetting: "Đang đặt lại...",
      featureSecure: "Bảo mật đa lớp với xác thực OTP",
      featureInstant: "Chuyển tiền tức thì, không giới hạn",
      featureAi: "Tư vấn chi tiêu & quản lý tài chính bằng AI",
      fillRequired: "Vui lòng nhập đầy đủ các trường yêu cầu.",
      loginFailed: "Đăng nhập thất bại.",
      serverError: "Kết nối máy chủ thất bại. Vui lòng kiểm tra kết nối Node.js/CSDL của bạn.",
      enterEmail: "Vui lòng nhập email của bạn.",
      invalidEmail: "Địa chỉ email không hợp lệ.",
      enterOtp: "Vui lòng nhập đầy đủ mã OTP 6 chữ số.",
      enterNewPass: "Vui lòng nhập mật khẩu mới.",
      passMinLength: "Mật khẩu phải có ít nhất 8 ký tự.",
      passNotMatch: "Mật khẩu xác nhận không trùng khớp.",
      resendOtp: "Gửi lại mã",
      resendCountdown: "Gửi lại mã sau {seconds} giây",
      otpExpiredAlert: "Mã OTP đã hết hạn hoặc không đúng.",
      brandTitle1: "Quản lý tài chính",
      brandTitle2: "thông minh hơn.",
      brandDesc: "SmartWallet giúp bạn quản lý thu chi, chuyển tiền tức thì và nhận tư vấn tài chính thông minh từ AI.",
      securityDesc: "Dữ liệu của bạn được mã hóa và bảo mật theo tiêu chuẩn ngân hàng SSL/TLS 256-bit.",
      copyright: "© 2026 Ví SmartWallet. Bảo lưu mọi quyền.",
    },
    footer: {
      contactUs: "Liên hệ",
      devTeam: "Nhóm phát triển:",
      devs: ["Lê Thị Kiều Duyên", "Lưu Anh Thuận", "Phạm Tấn Tài", "Châu Quốc Lâm Phong"],
      ourServices: "Dịch vụ của chúng tôi",
      shop: "Cửa hàng E-commerce",
      food: "Giao đồ ăn",
      reports: "Báo cáo tài chính",
      qr: "Thanh toán QR",
      map: "Bản đồ",
      ecosystem: "Hệ sinh thái SmartWallet",
      academicProject: "Dự án học thuật Node.js",
    },
    home: {
      analytics: "Thống kê SmartWallet",
      welcome: "Xin chào, {name} 👋",
      lead: "Theo dõi ví, giao dịch, dòng tiền và tin tức tài chính của bạn trong một không gian làm việc sạch sẽ.",
      deposit: "Nạp tiền",
      transfer: "Chuyển tiền",
      walletBalance: "Số dư Ví",
      totalIncome: "Tổng Thu nhập (7 ngày)",
      totalExpenses: "Tổng Chi tiêu (7 ngày)",
      transactions: "Giao dịch",
      availableBalance: "Số dư khả dụng",
      last7Days: "7 ngày qua",
      successfulRecords: "Giao dịch thành công",
      visitors: "Dòng tiền",
      cashFlowOverview: "Tổng quan dòng tiền từ hoạt động ví của bạn.",
      income: "Thu nhập",
      expense: "Chi tiêu",
      completed: "Đã hoàn thành",
      transactionSummary: "Tóm tắt giao dịch",
      transactionsCompleted: "giao dịch đã hoàn thành",
      totalIncomeLabel: "Tổng thu nhập",
      walletDistribution: "Phân bổ ví",
      incomeVsExpense: "Thu nhập và Chi tiêu",
      noData: "Không có dữ liệu",
      recentTransactions: "Giao dịch gần đây",
      latestActivity: "Hoạt động ví mới nhất",
      noRecentTxs: "Chưa có giao dịch gần đây.",
      financialNews: "Tin tức Tài chính",
      adminUpdates: "Cập nhật từ quản trị viên",
      noNews: "Không có tin tức nào.",
      aiAdvisorTitle: "Trợ lý tài chính AI",
      aiAdvisorDesc: "Hỏi SmartWallet AI để nhận mẹo chi tiêu, kế hoạch tiết kiệm và quyết định dòng tiền tốt hơn.",
      openAdvisor: "Mở Trợ lý AI",
    },
    profile: {
      title: "Cài đặt tài khoản",
      subtitle: "Quản lý ảnh đại diện, thông tin liên hệ và mật khẩu bảo mật.",
      section1: "1. Ảnh đại diện",
      section2: "2. Email & Số điện thoại",
      section3: "3. Thay đổi mật khẩu",
      section4: "4. Thay đổi mã PIN giao dịch",
      changeAvatar: "Thay đổi ảnh đại diện",
      changeName: "Sửa tên",
      emailLabel: "Địa chỉ Email",
      phoneLabel: "Số điện thoại",
      currentPassword: "Mật khẩu hiện tại",
      newPassword: "Mật khẩu mới",
      confirmNewPassword: "Xác nhận mật khẩu mới",
      updatePassword: "Cập nhật mật khẩu",
      nameCannotBeEmpty: "Tên không được để trống",
      avatarSuccess: "Ảnh đại diện đã được cập nhật thành công!",
      enterEmailPhone: "Vui lòng nhập email/SĐT hợp lệ.",
      otpTitle: "Xác thực bảo mật",
      otpSent: "Chúng tôi đã gửi mã xác thực đến",
      checkInbox: "Kiểm tra hộp thư đến (bao gồm cả thư mục Spam)",
      resendCode: "Gửi lại mã",
      resendIn: "Gửi lại sau {seconds} giây",
      submitOtp: "Xác nhận mã OTP",
      passwordUpdated: "Mật khẩu đã được cập nhật thành công!",
      enterAllFields: "Vui lòng nhập đầy đủ các trường",
      passwordsDoNotMatch: "Mật khẩu mới không trùng khớp",
      currentPin: "Mã PIN hiện tại",
      newPin: "Mã PIN mới",
      confirmNewPin: "Xác nhận mã PIN mới",
      updatePin: "Cập nhật mã PIN",
      pinUpdated: "Mã PIN giao dịch đã được cập nhật thành công!",
      pinLocked: "Mã PIN đang bị khóa. Vui lòng thử lại sau khi hết thời gian khóa.",
      noPinSet: "Bạn chưa thiết lập mã PIN. Vui lòng tạo mã PIN trong mục bên dưới.",
      pinsDoNotMatch: "Mã PIN mới không trùng khớp",
      pinMustBe4Digits: "Mã PIN phải gồm đúng 4 chữ số",
      forgotPin: "Quên mã PIN?",
      forgotPinTitle: "Đặt lại mã PIN giao dịch",
      forgotPinDesc: "Chúng tôi đã gửi mã OTP đến email đăng ký của bạn. Nhập OTP và mã PIN mới để đặt lại.",
      resetPin: "Đặt lại mã PIN",
      pinResetSuccess: "Mã PIN đã được đặt lại thành công!",
      section4Create: "4. Tạo mã PIN giao dịch",
      createPinDesc: "Thiết lập mã PIN 4 số để xác nhận chuyển tiền, rút tiền và các giao dịch quan trọng. Bạn cần xác thực OTP qua email trước khi tạo PIN.",
      createPin: "Tạo mã PIN",
      createPinTitle: "Tạo mã PIN giao dịch",
      createPinOtpDesc: "Chúng tôi đã gửi mã OTP đến email đăng ký của bạn. Nhập OTP và mã PIN mới để hoàn tất.",
      pinCreatedSuccess: "Mã PIN giao dịch đã được tạo thành công!",
    },
    investment: {
      title: "Tích lũy & Đầu tư",
      walletBalance: "Số dư ví thanh toán",
      remainingBalance: "Số dư còn lại sau khi gửi",
      activeSavings: "Số dư tích lũy hiện tại",
      projectedInterest: "Lãi suất dự kiến nhận",
      openAccount: "Mở tài khoản tiết kiệm",
      registerOnline: "Đăng ký trực tuyến để nhận lãi suất gấp đôi ngân hàng",
      enterAmount: "Số tiền tích lũy (VND)",
      selectTerm: "Chọn kỳ hạn",
      savingsTerm: "Kỳ hạn tích lũy",
      smartWalletRate: "Lãi suất SmartWallet",
      standardBankRate: "Lãi suất ngân hàng thường",
      estimatedInterest: "Lãi suất ước tính",
      totalMaturity: "Tổng gốc + lãi khi đáo hạn",
      whyChoose: "Tại sao chọn gửi tiết kiệm SmartWallet?",
      benefit1Title: "Lãi suất vượt trội",
      benefit1Desc: "Nhận tới 8.5% lãi suất năm, cao hơn đáng kể so với ngân hàng thường.",
      benefit2Title: "Kỳ hạn linh hoạt",
      benefit2Desc: "Chọn kỳ hạn linh hoạt từ 1 đến 12 tháng, hoặc chọn rút linh hoạt không kỳ hạn.",
      benefit3Title: "Rút tiền tức thì",
      benefit3Desc: "Rút tiền tích lũy linh hoạt bất kỳ lúc nào trực tiếp về ví thanh toán.",
      mySavings: "Tài khoản tích lũy của tôi",
      loading: "Đang tải danh sách tài khoản...",
      noAccounts: "Bạn chưa có tài khoản tích lũy nào đang hoạt động",
      openFirstAccount: "Mở tài khoản đầu tiên bằng cách điền form trên để nhận lãi suất cao!",
      accountNumber: "Tài khoản",
      termProgress: "Tiến độ kỳ hạn",
      appliedRate: "Lãi suất áp dụng",
      principalAmount: "Số tiền gốc",
      daysAccumulated: "Số ngày tích lũy",
      accruedInterest: "Lãi cộng dồn",
      flexibleTerm: "Không kỳ hạn",
      months: "tháng",
      earlyWithdrawalAlertTitle: "Xác nhận rút tiền trước hạn",
      earlyWithdrawalAlertText: "Bạn có chắc chắn muốn rút trước hạn không? Lãi suất sẽ bị hạ xuống mức phạt rút trước hạn là 0.2%/năm.",
      withdrawBtn: "Rút tiền tích lũy",
      days: "ngày",
      principalText: "Số tiền gốc",
      originalRateText: "Lãi suất gốc",
      effectiveRateText: "Lãi suất áp dụng thực tế",
      interestForfeitedText: "Lãi suất bị mất ước tính",
    },
    support: {
      title: "Hỗ trợ khách hàng",
      subtitle: "Trung tâm Hỗ trợ Khách hàng",
      hello: "Xin chào! Chúng tôi có thể giúp gì cho bạn hôm nay?",
      desc: "Gửi tin nhắn cho chúng tôi hoặc đính kèm ảnh chụp màn hình sự cố. Đội ngũ quản trị viên sẽ phản hồi bạn ngay tại đây.",
      imageSelected: "Đã chọn ảnh",
      typeMessage: "Nhập tin nhắn...",
      online: "Trực tuyến",
    },
    aiChatbot: {
      title: "Trợ lý tài chính AI",
      subtitle: "Trợ lý thông minh phân tích dòng tiền, chi tiêu và đưa ra các kế hoạch tích lũy tài chính dành riêng cho bạn.",
      online: "Trực tuyến",
      quickSuggestions: "Gợi ý nhanh câu hỏi",
      clickPrompt: "Click vào các câu hỏi gợi ý bên dưới để trợ lý phân tích dữ liệu ví của bạn ngay lập tức:",
      securityNotice: "Lưu ý bảo mật",
      securityDesc: "Dữ liệu phân tích dựa hoàn toàn vào lịch sử giao dịch ẩn danh của bạn trên hệ thống SmartWallet.",
      welcomeMsg: "Xin chào! Tôi là Trợ lý Tư vấn Tài chính AI của SmartWallet. Tôi có thể giúp gì cho bạn hôm nay? Bạn có thể yêu cầu tôi phân tích chi tiêu, gợi ý kế hoạch tiết kiệm hoặc tư vấn tối ưu hóa dòng tiền.",
      placeholder: "Nhập câu hỏi của bạn tại đây (ví dụ: Phân tích giúp tôi 10 giao dịch gần nhất)...",
      errorApiKey: "OPENAI_API_KEY chưa được cấu hình. Vui lòng thêm khóa OPENAI_API_KEY vào tệp .env của Backend.",
      errorGeneric: "Có lỗi xảy ra kết nối với hệ thống AI. Vui lòng kiểm tra và thử lại.",
      prompts: [
        "Phân tích chi tiêu của tôi gần đây",
        "Gợi ý cho tôi kế hoạch tiết kiệm 10 triệu đồng",
        "Tư vấn cách tối ưu số dư ví hiện tại",
        "Làm sao để hạn chế chi tiêu lãng phí?"
      ]
    },
    offersPage: {
      title: "Ưu đãi & Vouchers",
      subtitle: "Các ưu đãi độc quyền chỉ dành riêng cho thành viên SmartWallet",
      noOffers: "Không có ưu đãi nào khả dụng",
      hot: "HOT",
      exp: "Hạn dùng",
    },
    savings: {
      title: "Ví tiết kiệm (Piggy Banks)",
      subtitle: "Chia nhỏ nguồn tiền để tiết kiệm cho từng nhu cầu chi tiêu khác nhau",
      createVault: "Tạo Ví Tiết Kiệm Mới",
      vaultName: "Tên ví tiết kiệm",
      vaultNamePlaceholder: "Ví dụ: Đi du lịch, Mua laptop, Trà sữa...",
      targetAmount: "Mục tiêu (không bắt buộc)",
      category: "Danh mục",
      currentAmount: "Đã tiết kiệm",
      targetAmountLabel: "Mục tiêu",
      progress: "Đã hoàn thành",
      deposit: "Nạp tiền",
      withdraw: "Rút tiền",
      depositLabel: "Nạp vào ví",
      withdrawLabel: "Rút về ví chính",
      noVaults: "Bạn chưa tạo ví tiết kiệm nào. Hãy tạo một ví nhỏ để bắt đầu tích lũy nhé!",
      aiAccountant: "Thủ quỹ AI thông thái",
      aiWelcome: "Xin chào! Tôi là Trợ lý Thủ quỹ AI. Tôi sẽ giúp bạn phân tích chi tiêu và tạo động lực tiết kiệm tiền hiệu quả!",
      chatPlaceholder: "Nhập tin nhắn để hỏi ý kiến thủ quỹ...",
      send: "Gửi",
      amountToDeposit: "Số tiền nạp",
      amountToWithdraw: "Số tiền rút",
      depositSuccess: "Đã nạp tiền vào ví tiết kiệm thành công!",
      withdrawSuccess: "Đã rút tiền về ví chính thành công!",
      targetReached: "Chúc mừng! Bạn đã hoàn thành mục tiêu tiết kiệm này! 🎉",
      motivationalQuotes: [
        "Mỗi đồng tiết kiệm hôm nay là một bước đệm cho tự do tài chính ngày mai!",
        "Bớt đi một ly trà sữa 50k mỗi ngày, sau 1 năm bạn sẽ dư ra hơn 18 triệu đồng đấy!",
        "Tích tiểu thành đại! Đừng coi thường những khoản tiền nhỏ gửi vào ví tiết kiệm.",
        "Tiết kiệm không phải là keo kiệt, mà là đầu tư cho tương lai tự do của chính bạn.",
        "Hãy chuyển tiền tiết kiệm vào ví ngay ngày nhận lương, trước khi bạn kịp tiêu nó!",
        "Tiết kiệm trước, chi tiêu sau. Đó là bí quyết của người giàu có."
      ]
    },
    admin: {
      overview: "Tổng quan",
      manageUsers: "Quản lý người dùng",
      transactions: "Lịch sử giao dịch",
      manageInvestments: "Tích lũy & Đầu tư",
      suspiciousActivity: "Hoạt động nghi vấn",
      services: "Cấu hình dịch vụ",
      articles: "Quản lý tin tức",
      customerSupport: "Hỗ trợ khách hàng",
      logout: "Đăng xuất",
      logoutConfirmTitle: "Đăng xuất Admin?",
      logoutConfirmText: "Bạn sẽ được chuyển hướng về trang đăng nhập. Phiên làm việc hiện tại của bạn sẽ kết thúc.",
      cancel: "Hủy",
      adminRole: "Quản trị viên",
      adminPanel: "Bảng quản trị",
      feeRevenue: "Doanh thu phí",
      savingsAccounts: "Tài khoản tích lũy",
      idleMoney: "Tiền rảnh rỗi",
      projectedPayout: "Dự chi lãi",
      actualPaid: "Thực chi lãi",
      selectPeriod: "Chọn khoảng thời gian",
      today: "Hôm nay",
      thisMonth: "Tháng này",
      thisYear: "Năm nay",
      allTime: "Tất cả thời gian",
      chartTitle: "Biểu đồ doanh thu phí & giao dịch",
      systemOverview: "Tổng quan hệ thống",
      adminDashboard: "Bảng quản trị SmartWallet",
      savingsAccountsDesc: "Tài khoản tích lũy (đang hoạt động)",
      idleMoneyDesc: "Quỹ tiết kiệm + Đầu tư",
      projectedPayoutDesc: "Nợ lãi phải trả",
      actualPaidDesc: "Đã chi trả trong lịch sử",
      totalUsers: "Người dùng hệ thống",
      registeredAccounts: "Tài khoản đã đăng ký",
      noChartData: "Không có dữ liệu giao dịch trong khoảng thời gian này",
      totalTxVolume: "Tổng lượng giao dịch"
    },
    adminMedia: {
      title: "Quản lý bài viết",
      activeCount: "{count} bài viết tin tức tài chính đang hoạt động",
      newArticle: "Bài viết mới",
      coverImage: "Ảnh đại diện",
      articleTitle: "Tiêu đề bài viết",
      category: "Danh mục",
      timestamp: "Thời gian",
      visibility: "Hiển thị",
      visible: "Hiện",
      hidden: "Ẩn",
      editArticle: "Sửa bài viết",
      writeNewArticle: "Viết bài mới",
      titleVi: "Tiêu đề bài viết (VI)",
      titleEn: "Tiêu đề bài viết (EN)",
      aiGenerate: "✨ AI Tự động tạo",
      image: "Ảnh bài viết",
      upload: "Tải lên",
      redirectLink: "Đường dẫn chuyển hướng (Tùy chọn)",
      redirectDesc: "ví dụ: https://example.com/... (click vào thẻ sẽ mở link này)",
      contentVi: "Nội dung bài viết (VI)",
      contentEn: "Nội dung bài viết (EN)",
      writeViPlaceholder: "Viết nội dung bài viết chi tiết tại đây...",
      writeEnPlaceholder: "Write the full English article body here...",
      previewTitle: "XEM TRƯỚC BÀI VIẾT",
      previewPlaceholder: "Nội dung chi tiết bài viết sẽ hiển thị ở đây...",
      save: "Lưu",
      publish: "Đăng bài viết",
      update: "Cập nhật",
      cancel: "Hủy",
      confirmDelete: "Bạn có chắc chắn muốn xóa bài viết này không?",
      enterTitleFirst: "Vui lòng nhập tiêu đề trước khi tự động tạo bài viết!",
      aiGenerateFail: "Không thể tạo nội dung bài viết bằng AI.",
      aiGenerateError: "Lỗi hệ thống khi tạo bài viết bằng AI.",
      saveError: "Không thể lưu bài viết. Vui lòng thử lại.",
      deleteError: "Không thể xóa bài viết. Vui lòng thử lại.",
      toggleError: "Không thể chuyển đổi trạng thái hiển thị. Vui lòng thử lại.",
      noArticles: "Không tìm thấy bài viết nào",
      redirectPrefix: "Chuyển hướng:",
      aiWriting: "Đang viết... ⏳",
      titlePlaceholderVi: "Nhập tiêu đề bài viết...",
      titlePlaceholderEn: "Nhập tiêu đề bài viết (EN)...",
      otherOption: "Khác...",
      customCategoryPlaceholder: "Nhập danh mục khác...",
      imagePlaceholder: "Đường dẫn ảnh (picsum, unsplash...)",
      timestampPlaceholder: "VD: Vừa xong",
      titleSampleFallback: "Tiêu đề bài viết mẫu sẽ xuất hiện ở đây",
      tipLabel: "Mẹo:",
      tipText: "Kiểm tra kỹ tiêu đề và nội dung hiển thị ở trên. Đối với bài viết có đường dẫn chuyển hướng, click vào thẻ tin tức sẽ mở trang mới thay vì hiển thị nội dung bài viết.",
      confirmDeleteTitle: "Xác nhận xóa",
      deleteLabel: "Xóa",
      errorAlertTitle: "Thông báo lỗi",
      notificationTitle: "Thông báo",
      close: "Đóng"
    },
    adminSuspicious: {
      title: "Hoạt động nghi vấn",
      subtitle: "Tài khoản và giao dịch bị hệ thống đánh dấu có dấu hiệu rủi ro, gian lận hoặc bất thường.",
      totalAlerts: "Tổng cảnh báo",
      pendingReview: "Đang chờ duyệt",
      resolved: "Đã xử lý",
      detectedAlerts: "Cảnh báo phát hiện",
      autoMonitoring: "Tự động quét: Thời gian thực",
      viewDetails: "Xem chi tiết",
      dismissAlert: "Bỏ qua cảnh báo",
      alertDetails: "Chi tiết cảnh báo nghi vấn",
      alertId: "Mã cảnh báo",
      accountName: "Tên tài khoản",
      linkedEmail: "Email liên kết",
      behaviorType: "Loại hành vi",
      timeDetected: "Thời gian phát hiện",
      severityLevel: "Mức độ rủi ro",
      critical: "Nghiêm trọng (Cao)",
      medium: "Trung bình",
      low: "Thấp",
      systemReason: "Lý do hệ thống cảnh báo",
      immediateActions: "Hành động xử lý rủi ro khẩn cấp",
      unlockUser: "Mở khóa User",
      lockAccount: "Khóa tài khoản",
      unfreezeWallet: "Mở khóa Ví",
      freezeWallet: "Đóng băng Ví",
      userLockedBadge: "🔒 User bị khóa",
      walletFrozenBadge: "❄️ Ví bị đóng băng",
      confirmLock: "Khóa tài khoản cho {email}?\n\nNgười dùng sẽ không thể đăng nhập hoặc sử dụng ví.",
      confirmUnlock: "Mở khóa tài khoản cho {email}?\n\nNgười dùng sẽ lấy lại quyền truy cập.",
      confirmFreeze: "Đóng băng ví cho {email}?\n\nTất cả nạp, rút và chuyển tiền sẽ bị khóa.",
      confirmUnfreeze: "Mở khóa ví cho {email}?\n\nNgười dùng sẽ sử dụng lại được ví.",
      lockSuccess: "🔒 Khóa tài khoản thành công.",
      unlockSuccess: "🔓 Mở khóa tài khoản thành công.",
      freezeSuccess: "❄️ Đóng băng ví thành công!",
      unfreezeSuccess: "🔓 Mở khóa ví thành công!",
      resolveSuccess: "✅ Đã bỏ qua cảnh báo rủi ro thành công.",
      titleCritical: "Cảnh báo khẩn cấp",
      titleSecurity: "Cảnh báo bảo mật",
      userNotFound: "Không tìm thấy thông tin tài khoản người dùng.",
      disabledReactivateHint: "Tài khoản bị vô hiệu hóa phải được kích hoạt lại từ trang Người dùng.",
      errUpdateUserStatus: "Lỗi hệ thống khi cập nhật trạng thái tài khoản.",
      errUpdateWalletStatus: "Lỗi hệ thống khi cập nhật trạng thái ví.",
      errResolveAlert: "Lỗi hệ thống khi xử lý cảnh báo.",
      userLabel: "Người dùng:",
      confirmRequest: "Xác nhận yêu cầu",
      cancel: "Hủy",
      agree: "Đồng ý",
      errorAlertTitle: "Thông báo lỗi",
      notificationTitle: "Thông báo",
      close: "Đóng"
    },
    adminUsers: {
      title: "Quản lý người dùng",
      usersCount: "{count} người dùng",
      searchPlaceholder: "Tìm theo tên, email, ID...",
      details: "Chi tiết",
      noUsers: "Không tìm thấy người dùng nào",
      fallbackUser: "Người dùng",
      fallbackUserLower: "người dùng",
      notUpdated: "Chưa cập nhật",
      notProvided: "Chưa cung cấp",
      bank: "Ngân hàng",
      walletFrozen: "❄️ Đã đóng băng",
      walletActive: "🟢 Đang hoạt động",
      filters: { all: "Tất cả", verified: "Đã xác thực KYC", pending: "Chờ duyệt", none: "Chưa cung cấp KYC" },
      headers: { id: "ID", name: "Tên", email: "Email", kyc: "KYC", status: "Trạng thái", balance: "Số dư", actions: "Thao tác" },
      kyc: { verified: "Đã xác thực KYC", pending: "Chờ duyệt", rejected: "KYC bị từ chối", none: "Chưa cung cấp KYC" },
      status: { active: "Hoạt động", locked: "Đã khóa", disabled: "Đã vô hiệu hóa" },
      userModalTitle: "Người dùng: {name}",
      tabInfo: "Thông tin",
      tabIdDocs: "Giấy tờ tùy thân",
      tabTransactions: "Giao dịch",
      infoLabels: { id: "ID", email: "Email", phone: "Số điện thoại", kyc: "KYC", accountStatus: "Trạng thái tài khoản", walletStatus: "Trạng thái ví", balance: "Số dư", joined: "Ngày tham gia" },
      noIdDocs: "Người dùng này chưa nộp giấy tờ tùy thân hoặc chưa yêu cầu xác thực KYC.",
      cccdLabels: { nationalId: "Số CCCD/CMND", fullName: "Họ và tên", dob: "Ngày sinh", gender: "Giới tính", address: "Địa chỉ thường trú" },
      uploadedDocuments: "Giấy tờ đã tải lên",
      imgFront: "Mặt trước CCCD",
      imgBack: "Mặt sau CCCD",
      imgSelfie: "Ảnh selfie",
      referenceImages: "Ảnh tham chiếu (Thẻ CCCD gắn chip)",
      txTotal: "Tổng giao dịch",
      txSuccessful: "Thành công",
      txPending: "Đang xử lý",
      noTxHistory: "Chưa có lịch sử giao dịch",
      txStatusSuccess: "Thành công",
      txStatusPending: "Đang xử lý",
      txStatusFailed: "Thất bại",
      btnApproveKyc: "✅ Duyệt KYC",
      btnRejectKyc: "❌ Từ chối KYC",
      btnLockAccount: "Khóa tài khoản",
      btnUnlockAccount: "Mở khóa tài khoản",
      btnReactivate: "✅ Kích hoạt lại tài khoản",
      btnUnfreezeWallet: "❄️ Mở băng ví",
      btnFreezeWallet: "🔒 Đóng băng ví",
      btnClose: "Đóng",
      rejectModalTitle: "Từ chối hồ sơ KYC",
      rejectModalDesc: "Vui lòng nhập lý do từ chối hồ sơ xác thực để thông báo cho người dùng:",
      rejectPlaceholder: "Nhập lý do từ chối...",
      btnConfirm: "Xác nhận",
      btnCancel: "Hủy",
      defaultRejectReason: "Giấy tờ tùy thân không rõ ràng hoặc thông tin không khớp.",
      alertRejectReasonRequired: "Vui lòng nhập lý do từ chối KYC.",
      alertApproveSuccess: "✅ Đã duyệt KYC cho {name}!",
      alertRejectSuccess: "❌ Đã từ chối KYC của {name}.",
      alertLockSuccess: "🔒 Khóa tài khoản thành công.",
      alertUnlockSuccess: "✅ Mở khóa tài khoản thành công.",
      alertReactivateSuccess: "✅ Kích hoạt lại tài khoản thành công.",
      alertFreezeSuccess: "❄️ Đóng băng ví thành công.",
      alertUnfreezeSuccess: "✅ Mở băng ví thành công.",
      confirmLock: "Khóa tài khoản của {name}?\n\nNgười dùng sẽ không thể đăng nhập hoặc sử dụng các tính năng ví cho đến khi được mở khóa.",
      confirmUnlock: "Mở khóa tài khoản của {name}?\n\nNgười dùng sẽ lấy lại quyền truy cập vào tài khoản và ví.",
      confirmReactivate: "Kích hoạt lại tài khoản của {name}?",
      confirmFreeze: "Đóng băng ví của {name}?\n\nMọi giao dịch nạp, rút và chuyển tiền sẽ bị chặn cho đến khi được mở băng.",
      confirmUnfreeze: "Mở băng ví của {name}?\n\nNgười dùng sẽ có thể sử dụng lại các tính năng ví.",
      errorApprove: "Lỗi hệ thống khi duyệt KYC.",
      errorReject: "Lỗi hệ thống khi từ chối KYC.",
      errorLock: "Lỗi hệ thống khi thay đổi trạng thái tài khoản.",
      errorReactivate: "Lỗi hệ thống khi kích hoạt lại tài khoản.",
      errorFreeze: "Lỗi hệ thống khi thay đổi trạng thái ví."
    },
    adminTransactions: {
      userFallback: "Người dùng",
      toastLoadFailed: "Không thể tải danh sách giao dịch",
      toastApproveSuccess: "✅ Đã duyệt giao dịch {id} thành công",
      toastApproveFailed: "Không thể duyệt giao dịch",
      toastServerError: "Lỗi máy chủ",
      toastRejectSuccess: "❌ Đã từ chối giao dịch {id}",
      toastRejectFailed: "Không thể từ chối giao dịch",
      headerTitle: "📋 Quản lý giao dịch",
      headerSubtitle: "Duyệt và giám sát các yêu cầu nạp, rút và chuyển tiền từ người dùng",
      statTotalLabel: "Tổng giao dịch",
      statTotalDesc: "Lịch sử hệ thống",
      statPendingLabel: "Yêu cầu chờ duyệt",
      statPendingDesc: "Cần xử lý ngay",
      statCompletedLabel: "Đã hoàn thành",
      statCompletedDesc: "Giao dịch thành công",
      statFailedLabel: "Thất bại",
      statFailedDesc: "Giao dịch thất bại",
      searchPlaceholder: "Tìm theo mã giao dịch, tên người dùng hoặc nội dung...",
      statusAll: "Tất cả",
      statusPending: "Chờ duyệt",
      statusSuccess: "Thành công",
      statusFailed: "Thất bại",
      typeAll: "Tất cả loại",
      typeDeposit: "Nạp tiền",
      typeWithdrawTransfer: "Rút/Chuyển tiền",
      notePrefix: "Lời nhắn: ",
      pillSuccess: "Thành công",
      pillPending: "Chờ duyệt",
      pillFailed: "Thất bại",
      pillPendingApproval: "Chờ phê duyệt",
      btnApprove: "Duyệt",
      btnReject: "Từ chối",
      noMatchingTx: "Không tìm thấy giao dịch phù hợp",
      modalTitle: "Chi tiết yêu cầu giao dịch",
      rowTransactionId: "Mã giao dịch",
      rowTransactionType: "Loại giao dịch",
      valueDeposit: "Nạp tiền",
      valueWithdrawTransfer: "Rút/Chuyển tiền",
      rowCategory: "Danh mục",
      rowInitiatedBy: "Người thực hiện",
      rowCreatedAt: "Thời gian tạo",
      rowNoteDescription: "Lời nhắn / Mô tả"
    },
    adminInvestment: {
      pageTitle: "📈 Quản lý Tích lũy & Đầu tư",
      pageSubtitle: "Theo dõi toàn bộ tài khoản tích lũy và số dư đầu tư của tất cả người dùng",
      activeSavingsPrincipal: "Gốc tích lũy đang hoạt động",
      activeSavingsPrincipalDesc: "Tổng tiền gốc trên {count} tài khoản đang hoạt động",
      accruedInterestActive: "Lãi dồn tích (Đang hoạt động)",
      accruedInterestActiveDesc: "Lãi cộng dồn ước tính tính đến hiện tại",
      totalSettledPrincipal: "Tổng gốc đã tất toán",
      totalSettledPrincipalDesc: "Tiền gốc từ {count} tài khoản đã rút thành công",
      totalInterestPaidOut: "Tổng lãi đã chi trả",
      totalInterestPaidOutDesc: "Tổng tiền lãi đã thực chi về ví chính",
      filterAll: "Tất cả",
      filterActive: "Đang hoạt động",
      filterSettled: "Đã tất toán",
      searchPlaceholder: "Tìm theo email, số điện thoại hoặc ID...",
      loadingRecords: "Đang tải dữ liệu tích lũy...",
      noRecordsFound: "Không tìm thấy bản ghi tích lũy phù hợp",
      colId: "ID",
      colCustomer: "KHÁCH HÀNG",
      colPrincipal: "TIỀN GỐC",
      colTerm: "KỲ HẠN",
      colInterestRate: "LÃI SUẤT",
      colOpenDate: "NGÀY MỞ",
      colAccruedInterest: "LÃI DỒN TÍCH",
      colStatus: "TRẠNG THÁI",
      flexible: "Linh hoạt",
      termMonths: "{count} Tháng",
      maturity: "Đáo hạn: {date}",
      notAvailable: "Không có",
      statusSettled: "ĐÃ TẤT TOÁN",
      statusActive: "ĐANG HOẠT ĐỘNG",
      unknown: "Không rõ",
      noEmail: "Chưa có email"
    },
    adminServices: {
      pageTitle: "Quản lý dịch vụ",
      pageSubtitle: "Voucher, phí giao dịch và danh mục chi tiêu",
      addVoucher: "Thêm voucher",
      tabVoucher: "Voucher",
      tabFee: "Phí giao dịch",
      tabCategory: "Danh mục",
      colCode: "Mã",
      colDiscount: "Giảm giá",
      colType: "Loại",
      colExpiry: "Hạn dùng",
      colTitle: "Tiêu đề",
      colStatus: "Trạng thái",
      statusActive: "Đang bật",
      statusInactive: "Đã tắt",
      noVouchers: "Chưa có voucher nào. Nhấn \"+ Thêm voucher\" để bắt đầu.",
      addFee: "Thêm phí",
      noFees: "Chưa có quy tắc phí nào. Nhấn \"+ Thêm phí\" để tạo mới.",
      transactionTypePrefix: "Loại giao dịch: ",
      editBtn: "Sửa",
      deleteBtn: "Xóa",
      newCategoryPlaceholder: "Tên danh mục mới...",
      addCategoryBtn: "Thêm",
      editVoucherTitle: "Sửa voucher",
      addVoucherTitle: "Thêm voucher",
      labelCode: "Mã",
      placeholderCode: "VD: BLACKRED50",
      labelDisplayTitle: "Tiêu đề hiển thị",
      placeholderTitle: "VD: Tiết kiệm 50K phí chuyển tiền",
      labelShortDesc: "Mô tả ngắn",
      placeholderDesc: "VD: Áp dụng cho giao dịch từ 500K",
      labelDiscountType: "Loại giảm giá",
      optionFixed: "Cố định (₫)",
      optionPercentage: "Phần trăm (%)",
      labelValue: "Giá trị",
      placeholderValuePercent: "VD: 10",
      placeholderValueFixed: "VD: 50000",
      labelMinTransaction: "Giao dịch tối thiểu (₫)",
      placeholderMinTransaction: "0",
      labelQuantity: "Số lượng",
      placeholderQuantity: "VD: 100",
      labelExpiryDate: "Ngày hết hạn",
      labelStatus: "Trạng thái",
      labelTag: "Nhãn (marketing, dùng để lọc trang Ưu đãi)",
      hotEnabled: "HOT (đang bật)",
      markAsHot: "Đánh dấu HOT",
      hotBadgeHint: "Hiển thị huy hiệu 🔥 trên thẻ",
      cancelBtn: "Hủy",
      updateBtn: "Cập nhật",
      addNewBtn: "Thêm mới",
      editFeeTitle: "Sửa phí giao dịch",
      addFeeTitle: "Thêm phí giao dịch",
      labelTransactionType: "Loại giao dịch",
      labelFixedFee: "Phí cố định (VND)",
      placeholderFixedFee: "VD: 5000",
      saveChangesBtn: "Lưu thay đổi",
      failedToAddCategory: "Thêm danh mục thất bại",
      failedToDeleteCategory: "Xóa danh mục thất bại",
      feeValueInvalid: "Giá trị phí phải là số >= 0 (VND).",
      failedToSaveFee: "Lưu phí thất bại.",
      serverErrorSavingFee: "Lỗi máy chủ khi lưu phí.",
      deleteFeeConfirm: "Xóa quy tắc phí này?",
      errorDeletingFee: "Lỗi khi xóa phí.",
      enterCodeAndTitle: "Vui lòng nhập Mã và Tiêu đề!",
      discountValuePositive: "Giá trị giảm giá phải > 0",
      quantityPositive: "Số lượng phải > 0",
      selectExpiryDate: "Vui lòng chọn ngày hết hạn",
      failedToSaveVoucher: "Lưu voucher thất bại",
      serverErrorSavingVoucher: "Lỗi máy chủ khi lưu voucher",
      deleteVoucherConfirm: "Xóa voucher này?",
      errorDeletingVoucher: "Lỗi khi xóa voucher",
      errorUpdatingStatus: "Lỗi khi cập nhật trạng thái",
      txLabel: { TRANSFER: "Chuyển tiền nội bộ", WITHDRAW: "Rút/Chuyển khoản ngân hàng", PAYMENT: "Thanh toán", DEPOSIT: "Nạp tiền" }
    },
    adminSupport: {
      imageSizeError: "Kích thước ảnh không được vượt quá 5MB.",
      sendError: "Không thể gửi phản hồi. Vui lòng thử lại.",
      searchPlaceholder: "Tìm theo email hoặc số điện thoại...",
      noConversations: "Không tìm thấy cuộc trò chuyện hỗ trợ nào.",
      imageLabel: "📎 Hình ảnh",
      noMessagesYet: "Chưa có tin nhắn",
      phoneLabel: "Số điện thoại:",
      notAvailable: "Không có",
      attachmentAlt: "Tệp đính kèm",
      imageSelected: "Đã chọn ảnh",
      replyPlaceholder: "Trả lời {name}...",
      emptyTitle: "Trung tâm Hỗ trợ Khách hàng",
      emptyDesc: "Chọn một khách hàng từ danh sách bên trái để xem cuộc trò chuyện và gửi phản hồi."
    }
  },

  en: {
    nav: {
      home: "Home",
      about: "About",
      offers: "Offers",
      transfer: "Transfer",
      contact: "Contact",
      login: "Login",
      dashboard: "Dashboard",
      logout: "Logout",
      profile: "Profile",
      qrDeposit: "QR Deposit",
      myQr: "My QR",
      myWallets: "My Wallets",
      investment: "Investments & Savings",
      support: "Live Support",
      savingsVaults: "Savings Vaults",
    },
    index: {
      eyebrow: "SmartWallet Digital Finance",
      heroTitle1: "We Build Smooth",
      heroTitle2: "SmartWallet",
      heroTitle3: "Experiences For Modern Users.",
      heroLead:
        "Manage real-time balances, deposit and withdraw quickly, track spending with visual charts, and create personal savings goals.",
      getStarted: "Get Started →",
      ourServices: "Our Services",
      serviceTitle: "Featured Financial Services From SmartWallet",
      offerPrefix: "Offer #",
      offersCount: "offers",
      offerRunning: "Active offer",
      newsEyebrow: "SmartWallet Insights",
      newsTitle: "Latest Financial News",
      newsDesc:
        "Quick updates on announcements, offers, and digital finance trends published by SmartWallet admins.",
      viewAll: "View all",
      marketUpdate: "Market Update",
      readPost: "Read article",
      finance: "Finance",
      justNow: "Just now",
      newText: "New",
      featureTitle: "Premium Services With Smooth Micro Animation.",
      closeNews: "Close news detail",
      savingsTitle: "Smart Savings Vault",
      savingsSubtitle: "High yield, automated savings for your financial freedom",
      savingsInterestRate: "Up to 8.5% annual interest rate",
      savingsDesc: "SmartWallet offers the ultimate savings solution. Split your funds into separate goal-based vaults, track progress visually, and harness the power of compound interest.",
      savingsButton: "Start Saving Now",
      savingsFeature1Title: "High Interest Yield",
      savingsFeature1Desc: "Enjoy an attractive 8.5% annual yield, paid daily, keeping your money growing.",
      savingsFeature2Title: "Automated Saving",
      savingsFeature2Desc: "Set up rules to automatically sweep spare change or schedule recurring deposits into vaults.",
      savingsFeature3Title: "Flexible Withdrawals",
      savingsFeature3Desc: "No lock-in periods. Withdraw your funds back to your main wallet instantly at any time.",
    },
    cards: [
      {
        title: "💳 Deposit",
        desc: "Quickly top up your wallet from your bank account.",
      },
      {
        title: "💸 Transfer",
        desc: "Send money safely and instantly.",
      },
      {
        title: "🎁 Offers & Vouchers",
        desc: "Exclusive deals for SmartWallet users.",
      },
      {
        title: "📈 Investment",
        desc: "Smart investing with flexible financial packages.",
      },
    ],
    offers: [
      {
        title: "20% transaction fee discount",
        description: "Applies to transfers and QR payments.",
      },
      {
        title: "Wallet top-up voucher",
        description: "Get a special offer on your first wallet top-up.",
      },
      {
        title: "QR cashback",
        description: "Get cashback when paying by QR at supported stores.",
      },
    ],
    news: [
      {
        title: "SmartWallet updates real-time transaction security",
        tag: "Digital Finance",
        time: "Just now",
        content:
          "Track balance changes, receive transaction alerts, and protect your e-wallet with a faster and clearer SmartWallet experience.",
      },
      {
        title: "Transfer fee offers for new users",
        tag: "Offers",
        time: "Today",
        content:
          "New voucher campaigns help users save money when transferring, topping up, and paying by QR.",
      },
      {
        title: "Manage personal spending with smart charts",
        tag: "Money Management",
        time: "1 day ago",
        content:
          "SmartWallet helps categorize cash flow, summarize income and expenses, and support better financial decisions.",
      },
    ],
    features: [
      {
        title: "Account Security",
        desc: "Protect your wallet with KYC, transaction PIN, and instant alerts.",
      },
      {
        title: "Flexible Payments",
        desc: "Deposit, withdraw, transfer, and make bank payments in one ecosystem.",
      },
      {
        title: "Financial Management",
        desc: "Track income, expenses, offers, and balance changes more clearly.",
      },
    ],
    dashboard: {
      availableBalance: "Available Balance",
      active: "ACTIVE",
      frozen: "FROZEN",
      deposit: "Deposit",
      withdraw: "Withdraw",
      transfer: "Transfer",
      qrCode: "QR Code",
      linkedBanks: "Linked Banks",
      accountsLinked: "accounts linked",
      addBank: "Add Bank",
      transactionHistory: "Transaction History",
      searchTransactions: "Search transactions...",
      all: "All",
      receive: "Receive",
      send: "Send",
      success: "Success",
      pending: "Processing",
      failed: "Failed",
      noTransactions: "No transactions found",
    },
    wallets: {
      freezeConfirmTitle: "Freeze Your Wallet?",
      freezeConfirmText: "This action cannot be undone by you. Freezing your wallet will immediately disable all deposits, withdrawals, and transfers. Only our support team can unfreeze it.",
      freezeButton: "Freeze Now",
      cancel: "Cancel",
      walletFrozenBanner: "Wallet Frozen. All transactions are disabled. To restore access, please contact support.",
      contactSupport: "Contact Support",
      pinSetupTitle: "Set Up Transaction PIN",
      pinSetupText: "Please choose a 4-digit PIN to use when transferring or withdrawing funds.",
      enterNewPin: "Enter new PIN (4 digits)",
      confirmNewPin: "Confirm new PIN",
      confirmAndSet: "Confirm & Set Up",
      enterPinToConfirm: "Enter transaction PIN to confirm",
      depositTitle: "Deposit to Wallet",
      depositSuccess: "Deposit successful! Your balance has been updated.",
      minimumDeposit: "Minimum deposit is 1,000₫!",
      selectLinkedBank: "Select a linked bank account:",
      amountToDeposit: "Amount to deposit:",
      note: "Note:",
      depositViaBank: "Deposit via Linked Bank",
      depositViaPayos: "Deposit via QR Bank (PayOS)",
      processing: "Processing...",
      withdrawTitle: "Withdraw to Bank",
      withdrawMin: "Minimum withdrawal is 10,000₫!",
      selectBankWithdraw: "Select destination bank account:",
      transferTitle: "Transfer Money",
      transferMethod: "Transfer Method:",
      viaEmailPhone: "Via Email / Phone",
      viaBankSandbox: "Via Bank Sandbox",
      recipientEmail: "Recipient Email/Phone:",
      amountToTransfer: "Amount to transfer:",
      selectCategory: "Select transaction category:",
      applyVoucher: "Apply Discount Code:",
      placeholderVoucher: "Enter voucher code...",
      apply: "Apply",
      appliedVoucher: "Applied voucher",
      saveText: "saved",
      chooseVoucher: "Choose Available Voucher",
      linkedBanksList: "Linked Bank Accounts",
      unlink: "Unlink",
      bankName: "Bank Name",
      accountNumber: "Account Number",
      accountHolder: "Account Holder",
      linkNewBank: "Link New Bank",
      selectBank: "Select Bank",
      submit: "Submit",
      depositDesc: "Add funds to your SmartWallet account",
      selectDepositMethod: "Select deposit method",
      depositFromLinkedBankTitle: "🏦 Deposit from Linked Bank",
      noLinkedBanksDesc: "Please link a bank account to make a deposit",
      linkBankNow: "Link a Bank Now",
      confirmDeposit: "Confirm Deposit",
      bankTransferDepositTitle: "📱 Bank Transfer Deposit",
      bankTransferDepositDesc: "Please scan the QR code or manually transfer to the admin account below",
      checkingStatus: "System is automatically checking transaction status...",
      openPayosPage: "🔗 Open PayOS Payment Page (Test Mode)",
      iHaveTransferred: "I Have Transferred",
      withdrawDesc: "Withdraw to your bank account",
      withdrawAmountLabel: "Withdrawal amount (₫)",
      confirmWithdrawBtn: "Confirm Withdrawal",
      withdrawPinDesc: "Please enter your 4-digit transaction PIN to confirm the withdrawal.",
      confirmWithdrawalTitle: "Confirm Withdrawal",
      transferDesc: "Fast and secure money transfer",
      uploadQrTitle: "Upload bank QR code image (optional)",
      clickToUploadQr: "Click to upload QR image",
      orEnterManually: "or enter manually",
      recipientAccount: "Recipient's account number *",
      recipientOwner: "Account holder name (optional)",
      enterAccountPlaceholder: "Enter account number",
      enterOwnerPlaceholder: "Full name of recipient",
      promoRewardTitle: "Promo Codes & Rewards",
      browsePromoCodes: "Browse available codes",
      removePromo: "Remove",
      appliedPromo: "Applied",
      discountPromo: "Discount",
      enterVoucherAmountAlert: "Please enter an amount before applying a promo code!",
      confirmTransferBtn: "Confirm Transfer",
      confirmTransferDiscountedBtn: "Confirm Transfer (Discounted)",
      selectPromoTitle: "Select Promo Code",
      minTxnAmount: "Min Txn",
      expDate: "Exp",
      linkLimitReachedTitle: "Link Limit Reached",
      linkLimitReachedDesc: "You have reached the maximum of 3 linked banks. Please remove an existing bank before adding a new one.",
      linkedBanksProgress: "Linked banks",
      onlyOneSlotRemaining: "⚠️ Only 1 slot remaining!",
      bankAccountsLinkedToWallet: "Bank accounts linked to your wallet:",
      addNewBankLink: "+ Add New Bank Link",
      txDetailTitle: "Transaction Details",
      txDetailAmount: "Amount",
      txDetailId: "Transaction ID",
      txDetailType: "Type",
      txDetailCategory: "Category",
      txDetailSender: "Sender",
      txDetailRecipient: "Recipient",
      txDetailDate: "Date & Time",
      txDetailNote: "Note",
      serviceFee: "Service fee",
      noFee: "No fee",
      feePerTxnHint: "Fee will be added to the total once you enter an amount",
      totalDeduction: "Total deducted from wallet",
      txDetailFee: "Transaction fee",
      txDetailTotal: "Total charged",
      discount: "Discount",
      cannotBeUndone: "This action cannot be undone",
      depositAmount: "Deposit amount",
      noLinkedBanks: "No linked bank accounts",
      bankNameLabel: "Bank",
      accountNumberLabel: "Account Number",
      accountHolderLabel: "Account Holder",
      amountLabel: "Amount",
      transferNoteLabel: "Transfer Note",
      copyBtn: "Copy",
      copiedToast: "Copied",
      enterPinTransferDesc: "Please enter your 4-digit transaction PIN to confirm the transfer.",
      smartwalletTransferInfo: "Transfer directly to a SmartWallet account using a registered phone number or email.",
      bankTransferInfo: "Upload a bank QR image or manually enter the recipient's bank and account number.",
      changeImage: "Change Image",
      banksCountLabel: "banks",
      removeBtn: "Remove",
      linkedCountLabel: "linked",
      noLinkedBanksDescWithdraw: "Please add a bank account to easily deposit and withdraw funds.",
      kycVerifiedStatus: "Account verified ✓",
      kycPendingStatus: "KYC pending review ⏳",
      kycUnverifiedStatus: "KYC not verified ⚠️",
      scanningQr: "Reading QR Code...",
      qrTransferPayment: "QR transfer payment",
      qrScanSuccess: "QR Code parsed successfully! Recipient info filled.",
      depositViaBankDesc: "Instant deposit from your linked bank account",
      depositViaPayosDesc: "Generate a QR code for the deposit amount",
      mbBankAdmin: "MB Bank (Military Bank)",
      bankLabel: "Bank",
      enterPhoneEmailPlaceholder: "Enter phone number or email",
    },
    kyc: {
      title: "Identity Verification (KYC)",
      subtitle: "Verify your identity to increase transaction limits and unlock all features.",
      verifiedTitle: "Identity Verified",
      verifiedDesc: "Your transaction limits have been upgraded to the maximum level.",
      verifiedInfo: "Verified Personal Information",
      fullName: "Full Name",
      nationalId: "National ID",
      dob: "Date of Birth",
      gender: "Gender",
      address: "Permanent Address",
      documentsTitle: "ID Documents & Portrait",
      idFront: "ID Card – Front",
      idBack: "ID Card – Back",
      selfie: "Selfie Portrait",
      noImage: "No image",
      requestUpdate: "Request KYC Information Update",
      underReviewTitle: "Application Under Review",
      underReviewDesc: "We have received your KYC application and it is currently under review. Please wait for 1-3 business days.",
      rejectedTitle: "KYC Application Rejected",
      rejectedDesc: "Please review your uploaded information and documents and submit again.",
      personalInfo: "Personal Info",
      uploadDocuments: "Upload Documents",
      underReviewStep: "Under Review",
      next: "Next",
      back: "Back",
      submitKyc: "Submit for Verification",
      uploadPrompt: "Choose image",
      alertNote: "Photos must be clear, unblurred, and unobstructed. Accepted formats: JPG / PNG / WEBP / GIF, max 5 MB.",
    },
    myQr: {
      title: "Your QR Code",
      subtitle: "Show this QR code to others to receive transfers directly into your SmartWallet.",
      userId: "User ID",
      email: "Receiver Email",
      downloadQr: "Download QR",
      copyQr: "Copy QR",
      copied: "Copied",
      transfer: "Transfer",
    },
    qrSandbox: {
      title: "SmartWallet Sandbox QR Deposit",
      subtitle: "Create a mockup QR code to deposit simulated funds into your SmartWallet.",
      createTitle: "Create QR Deposit",
      amountLabel: "Deposit Amount",
      amountPlaceholder: "e.g. 100000",
      createBtn: "Create QR Deposit",
      creating: "Creating QR...",
      demoFlowTitle: "Sandbox Demo Flow:",
      step1: "1. Enter the deposit amount.",
      step2: "2. Click simulation button to mimic bank payment and credit your wallet.",
      paymentTitle: "QR Payment",
      noQrText: "No QR generated. Enter an amount and click generate.",
      amount: "Amount",
      reference: "Reference",
      status: "Status",
      simulateScanBtn: "Simulate scan & payment",
      simulating: "Simulating payment...",
      successTitle: "Deposit Successful",
      failedTitle: "Transaction Failed",
      newBalance: "New Balance",
    },
    notifications: {
      title: "Your Notifications",
      subtitle: "View and manage all transaction and security notifications.",
      empty: "No notifications found.",
      markAllRead: "Mark all as read",
      read: "Read",
      unread: "Unread",
      time: "Time",
      viewAll: "View all notifications",
    },
    login: {
      title: "Sign In to SmartWallet",
      desc: "Enter your email and password to access your digital wallet dashboard.",
      emailLabel: "Email Address",
      passLabel: "Password",
      forgotPass: "Forgot Password?",
      loginBtn: "Login",
      loggingIn: "Logging in...",
      needAccount: "Don't have an account?",
      registerNow: "Register now",
      registerTitle: "Create an Account",
      registerDesc: "Create a new SmartWallet account to start managing your finance.",
      phoneLabel: "Phone Number",
      confirmPassLabel: "Confirm Password",
      registerBtn: "Register",
      registering: "Registering...",
      haveAccount: "Already have an account?",
      loginNow: "Login now",
      forgotModalTitle: "Recover Password",
      forgotModalDesc: "Enter your email address to receive recovery OTP.",
      sendOtp: "Send OTP",
      sending: "Sending...",
      backToLogin: "Back to login",
      enterOtpDesc: "Enter the 6-digit OTP code sent to your email.",
      resetPassTitle: "Reset New Password",
      resetPassDesc: "Enter a new password for your account.",
      newPassLabel: "New Password",
      resetBtn: "Reset Password",
      resetting: "Resetting...",
      featureSecure: "Multi-layer security with OTP authentication",
      featureInstant: "Instant transfers with no limits",
      featureAi: "AI-powered spending advice and management",
      fillRequired: "Please fill in all required fields.",
      loginFailed: "Login failed.",
      serverError: "Server connection failed. Please check your Node.js/DB connection.",
      enterEmail: "Please enter your email.",
      invalidEmail: "Invalid email address.",
      enterOtp: "Please enter the complete 6-digit OTP code.",
      enterNewPass: "Please enter a new password.",
      passMinLength: "Password must be at least 8 characters.",
      passNotMatch: "Passwords do not match.",
      resendOtp: "Resend code",
      resendCountdown: "Resend code in {seconds}s",
      otpExpiredAlert: "OTP code has expired or is incorrect.",
      brandTitle1: "Smarter financial",
      brandTitle2: "management.",
      brandDesc: "SmartWallet helps you track spending, send money instantly, and receive smart financial insights powered by AI.",
      securityDesc: "Your data is encrypted and secured by 256-bit SSL/TLS banking-grade standards.",
      copyright: "© 2026 SmartWallet Wallet. All rights reserved.",
    },
    footer: {
      contactUs: "Contact US",
      devTeam: "Development Team:",
      devs: ["Le Thi Kieu Duyen", "Luu Anh Thuan", "Pham Tan Tai", "Chau Quoc Lam Phong"],
      ourServices: "Our Services",
      shop: "E-commerce Shop",
      food: "Food Delivery",
      reports: "Financial Reports",
      qr: "QR Payment",
      map: "Map",
      ecosystem: "SmartWallet Ecosystem",
      academicProject: "Node.js Academic Project",
    },
    home: {
      analytics: "SmartWallet Analytics",
      welcome: "Hello, {name} 👋",
      lead: "Monitor your wallet, transactions, cash flow and financial news in one clean workspace.",
      deposit: "Deposit",
      transfer: "Transfer",
      walletBalance: "Wallet Balance",
      totalIncome: "Total Income (7 Days)",
      totalExpenses: "Total Expenses (7 Days)",
      transactions: "Transactions",
      availableBalance: "Available balance",
      last7Days: "Last 7 days",
      successfulRecords: "Successful transactions",
      visitors: "Cash Flow",
      cashFlowOverview: "Cash flow overview from your wallet activity.",
      income: "Income",
      expense: "Expense",
      completed: "Completed",
      transactionSummary: "Transaction summary",
      transactionsCompleted: "transactions completed",
      totalIncomeLabel: "Total income",
      walletDistribution: "Wallet Distribution",
      incomeVsExpense: "Income vs Expense",
      noData: "No Data",
      recentTransactions: "Recent Transactions",
      latestActivity: "Latest wallet activity",
      noRecentTxs: "No recent transactions.",
      financialNews: "Financial News",
      adminUpdates: "Admin updates",
      noNews: "No news yet.",
      aiAdvisorTitle: "AI Financial Advisor",
      aiAdvisorDesc: "Ask SmartWallet AI for spending tips, saving plans and better cash-flow decisions.",
      openAdvisor: "Open Advisor",
    },
    profile: {
      title: "Account Settings",
      subtitle: "Manage your profile picture, contact information, and security password.",
      section1: "1. Profile Picture",
      section2: "2. Email & Phone Number",
      section3: "3. Change Password",
      section4: "4. Change Transaction PIN",
      changeAvatar: "Change Avatar",
      changeName: "Edit Name",
      emailLabel: "Email Address",
      phoneLabel: "Phone Number",
      currentPassword: "Current Password",
      newPassword: "New Password",
      confirmNewPassword: "Confirm New Password",
      updatePassword: "Update Password",
      nameCannotBeEmpty: "Name cannot be empty",
      avatarSuccess: "Avatar updated successfully!",
      enterEmailPhone: "Please enter a valid email/phone.",
      otpTitle: "Security Verification",
      otpSent: "We have sent a verification code to",
      checkInbox: "Check your inbox (including Spam folder)",
      resendCode: "Resend code",
      resendIn: "Resend in {seconds}s",
      submitOtp: "Submit Verification",
      passwordUpdated: "Password updated successfully!",
      enterAllFields: "Please fill in all fields",
      passwordsDoNotMatch: "New passwords do not match",
      currentPin: "Current PIN",
      newPin: "New PIN",
      confirmNewPin: "Confirm New PIN",
      updatePin: "Update PIN",
      pinUpdated: "Transaction PIN updated successfully!",
      pinLocked: "Your PIN is locked. Please try again after the lock period ends.",
      noPinSet: "You have not set a transaction PIN yet. Please create one in the section below.",
      pinsDoNotMatch: "New PINs do not match",
      pinMustBe4Digits: "PIN must be exactly 4 digits",
      forgotPin: "Forgot PIN?",
      forgotPinTitle: "Reset Transaction PIN",
      forgotPinDesc: "We sent an OTP to your registered email. Enter the OTP and your new PIN to reset.",
      resetPin: "Reset PIN",
      pinResetSuccess: "Transaction PIN reset successfully!",
      section4Create: "4. Create Transaction PIN",
      createPinDesc: "Set up a 4-digit PIN to confirm transfers, withdrawals, and other important transactions. Email OTP verification is required before creating your PIN.",
      createPin: "Create PIN",
      createPinTitle: "Create Transaction PIN",
      createPinOtpDesc: "We sent an OTP to your registered email. Enter the OTP and your new PIN to finish setup.",
      pinCreatedSuccess: "Transaction PIN created successfully!",
    },
    investment: {
      title: "Investments & Savings",
      walletBalance: "Payment Wallet Balance",
      remainingBalance: "Remaining after deposit",
      activeSavings: "Active Savings",
      projectedInterest: "Projected Interest (Accrued)",
      openAccount: "Open a Savings Account",
      registerOnline: "Register online to earn double the bank interest rate",
      enterAmount: "Amount to save (VND)",
      selectTerm: "Select Term",
      savingsTerm: "Savings term",
      smartWalletRate: "SmartWallet Rate",
      standardBankRate: "Standard Bank Rate",
      estimatedInterest: "Estimated Interest",
      totalMaturity: "Total Principal + Interest at Maturity",
      whyChoose: "Why Choose SmartWallet Savings?",
      benefit1Title: "High Yield Rates",
      benefit1Desc: "Earn up to 8.5% annual interest, significantly higher than standard bank rates.",
      benefit2Title: "Flexible Options",
      benefit2Desc: "Choose flexible terms from 1 to 12 months, or choose flexible non-term withdrawal.",
      benefit3Title: "Instant Payouts",
      benefit3Desc: "Withdraw your flexible savings at any time directly back to your payment wallet.",
      mySavings: "My Savings Accounts",
      loading: "Loading your savings accounts...",
      noAccounts: "You have no active savings accounts yet",
      openFirstAccount: "Open your first account using the form above and earn double the bank rate!",
      accountNumber: "Account",
      termProgress: "Term Progress",
      appliedRate: "Applied Interest Rate",
      principalAmount: "Principal Amount",
      daysAccumulated: "Days Accumulated",
      accruedInterest: "Accrued Interest",
      flexibleTerm: "Flexible Term",
      months: "months",
      earlyWithdrawalAlertTitle: "Early Withdrawal Confirmation",
      earlyWithdrawalAlertText: "Are you sure you want to withdraw early? Your interest rate will be reduced to 0.2%/year penalty rate.",
      withdrawBtn: "Withdraw Savings",
      days: "days",
      principalText: "Principal Amount",
      originalRateText: "Original Term Rate",
      effectiveRateText: "Effective Rate Applied",
      interestForfeitedText: "Estimated Interest Forfeited",
    },
    support: {
      title: "Live Support",
      subtitle: "Customer Support Center",
      hello: "Hello! How can we help you today?",
      desc: "Send us a message or attach a screenshot of the issue. Our admin team will respond to you right here.",
      imageSelected: "Image selected",
      typeMessage: "Type a message...",
      online: "Online",
    },
    aiChatbot: {
      title: "AI Financial Advisor",
      subtitle: "Smart assistant analyzing cash flow, spending, and providing customized financial savings plans just for you.",
      online: "Online",
      quickSuggestions: "Quick Suggestions",
      clickPrompt: "Click on the suggested questions below to have the assistant analyze your wallet data immediately:",
      securityNotice: "Security Notice",
      securityDesc: "Analysis data is based entirely on your anonymous transaction history on the SmartWallet system.",
      welcomeMsg: "Hello! I am the SmartWallet AI Financial Advisor. How can I help you today? You can ask me to analyze spending, suggest savings plans or optimize cash flow.",
      placeholder: "Type your question here (e.g. Help me analyze my 10 recent transactions)...",
      errorApiKey: "OPENAI_API_KEY is not configured. Please add the OPENAI_API_KEY key to the Backend .env file.",
      errorGeneric: "An error occurred connecting to the AI system. Please check and try again.",
      prompts: [
        "Analyze my recent spending",
        "Suggest a savings plan for 10 million VND",
        "Advise how to optimize my current wallet balance",
        "How to reduce waste spending?"
      ]
    },
    offersPage: {
      title: "Offers & Vouchers",
      subtitle: "Exclusive deals available only for SmartWallet members",
      noOffers: "No offers available",
      hot: "HOT",
      exp: "Exp",
    },
    savings: {
      title: "Savings Vaults",
      subtitle: "Split your funds into custom sub-wallets to save for personal goals",
      createVault: "Create New Savings Vault",
      vaultName: "Vault Name",
      vaultNamePlaceholder: "e.g., Summer Trip, Buy Laptop, Bubble Tea...",
      targetAmount: "Target Amount (Optional)",
      category: "Category",
      currentAmount: "Saved",
      targetAmountLabel: "Target",
      progress: "Progress",
      deposit: "Deposit",
      withdraw: "Withdraw",
      depositLabel: "Deposit to Vault",
      withdrawLabel: "Withdraw to Wallet",
      noVaults: "You don't have any savings vaults yet. Create one to start saving!",
      aiAccountant: "AI Financial Accountant",
      aiWelcome: "Hello! I am your AI Accountant Advisor. I will help you track budgets and stay motivated to achieve your savings goals!",
      chatPlaceholder: "Type a message to ask your accountant...",
      send: "Send",
      amountToDeposit: "Amount to Deposit",
      amountToWithdraw: "Amount to Withdraw",
      depositSuccess: "Successfully deposited money to savings vault!",
      withdrawSuccess: "Successfully withdrew money back to main wallet!",
      targetReached: "Congratulations! You have achieved your savings goal! 🎉",
      motivationalQuotes: [
        "A penny saved today is a stepping stone to financial freedom tomorrow!",
        "Skipping one 50k bubble tea daily leaves you with over 18 million VND after a year!",
        "Little by little, a little becomes a lot! Keep feeding your savings vaults.",
        "Savings is not about restriction; it is an investment in your future self.",
        "Move money to your savings vaults as soon as you get paid, before you can spend it!",
        "Save first, spend what is left. That is the secret to building wealth."
      ]
    },
    admin: {
      overview: "Overview",
      manageUsers: "Manage Users",
      transactions: "Transactions",
      manageInvestments: "Manage Investments",
      suspiciousActivity: "Suspicious Activity",
      services: "Services",
      articles: "Articles",
      customerSupport: "Customer Support",
      logout: "Log Out",
      logoutConfirmTitle: "Log Out Admin?",
      logoutConfirmText: "You will be redirected to the login page. Your current session will end.",
      cancel: "Cancel",
      adminRole: "Admin",
      adminPanel: "Admin Panel",
      feeRevenue: "Fee Revenue",
      savingsAccounts: "Savings Accounts",
      idleMoney: "Idle Money",
      projectedPayout: "Projected Interest Payout",
      actualPaid: "Actual Interest Paid",
      selectPeriod: "Select Period",
      today: "Today",
      thisMonth: "This Month",
      thisYear: "This Year",
      allTime: "All Time",
      chartTitle: "Fee Revenue & Transaction Chart",
      systemOverview: "System Overview",
      adminDashboard: "SmartWallet Admin Dashboard",
      savingsAccountsDesc: "Savings accounts (active)",
      idleMoneyDesc: "Vaults + Investments",
      projectedPayoutDesc: "Outstanding liability",
      actualPaidDesc: "Paid historically",
      totalUsers: "Total Users",
      registeredAccounts: "Registered accounts",
      noChartData: "No transaction data available for this period",
      totalTxVolume: "Total Tx Volume"
    },
    adminMedia: {
      title: "Article Management",
      activeCount: "{count} financial news articles active",
      newArticle: "New Article",
      coverImage: "Cover Image",
      articleTitle: "Article Title",
      category: "Category",
      timestamp: "Timestamp",
      visibility: "Visibility",
      visible: "Visible",
      hidden: "Hidden",
      editArticle: "Edit Article",
      writeNewArticle: "Write New Article",
      titleVi: "Article Title (VI)",
      titleEn: "Article Title (EN)",
      aiGenerate: "✨ AI Auto-Generate",
      image: "Article Image",
      upload: "Upload",
      redirectLink: "Redirect Link (Optional)",
      redirectDesc: "e.g. https://example.com/... (clicking the card will open this link)",
      contentVi: "Article Body (VI)",
      contentEn: "Article Body (EN)",
      writeViPlaceholder: "Viết nội dung bài viết chi tiết tại đây...",
      writeEnPlaceholder: "Write the full English article body here...",
      previewTitle: "ARTICLE PREVIEW",
      previewPlaceholder: "The full article body written by the admin will automatically appear in the user's detail view when they tap the article card...",
      save: "Save",
      publish: "Publish Article",
      update: "Update",
      cancel: "Cancel",
      confirmDelete: "Are you sure you want to delete this article?",
      enterTitleFirst: "Please enter a title first!",
      aiGenerateFail: "Failed to generate article content.",
      aiGenerateError: "An error occurred during AI article generation.",
      saveError: "Unable to save article. Please try again.",
      deleteError: "Unable to delete article. Please try again.",
      toggleError: "Unable to toggle article visibility. Please try again.",
      noArticles: "No articles found",
      redirectPrefix: "Redirect:",
      aiWriting: "Writing... ⏳",
      titlePlaceholderVi: "Enter article title...",
      titlePlaceholderEn: "Enter English title...",
      otherOption: "Other...",
      customCategoryPlaceholder: "Enter custom category...",
      imagePlaceholder: "Image URL (picsum, unsplash...)",
      timestampPlaceholder: "e.g. Just now",
      titleSampleFallback: "Sample article title will appear here",
      tipLabel: "Tip:",
      tipText: "Double-check the title and content displayed above. For articles with a redirect link, clicking the news card will open a new page instead of showing the article body.",
      confirmDeleteTitle: "Confirm Delete",
      deleteLabel: "Delete",
      errorAlertTitle: "Error Alert",
      notificationTitle: "Notification",
      close: "Close"
    },
    adminSuspicious: {
      title: "Suspicious Transactions & Accounts",
      subtitle: "Accounts and transactions flagged by the system as showing signs of risk, fraud, or system anomalies.",
      totalAlerts: "Total Alerts",
      pendingReview: "Pending Review",
      resolved: "Resolved",
      detectedAlerts: "Detected Alerts",
      autoMonitoring: "Auto-monitoring: Real-time",
      viewDetails: "View Details",
      dismissAlert: "Dismiss Alert",
      alertDetails: "Suspicious Alert Details",
      alertId: "Alert ID",
      accountName: "Account Name",
      linkedEmail: "Linked Email",
      behaviorType: "Behavior Type",
      timeDetected: "Time Detected",
      severityLevel: "Severity Level",
      critical: "🔴 Critical (High)",
      medium: "🟡 Medium",
      low: "🔵 Low",
      systemReason: "System Flagged Reason",
      immediateActions: "Immediate Risk Actions",
      unlockUser: "Unlock User",
      lockAccount: "Lock Account",
      unfreezeWallet: "Unfreeze Wallet",
      freezeWallet: "Freeze Wallet",
      userLockedBadge: "🔒 User Locked",
      walletFrozenBadge: "❄️ Wallet Frozen",
      confirmLock: "Lock account for {email}?\n\nThe user will not be able to sign in or use wallet features until unlocked.",
      confirmUnlock: "Unlock account for {email}?\n\nThe user will regain access to their account and wallet.",
      confirmFreeze: "Freeze wallet for {email}?\n\nAll deposits, withdrawals, and transfers will be blocked until unfrozen.",
      confirmUnfreeze: "Unfreeze wallet for {email}?\n\nThe user will be able to use wallet features again.",
      lockSuccess: "🔒 Account locked successfully.",
      unlockSuccess: "🔓 Account unlocked successfully.",
      freezeSuccess: "❄️ Wallet frozen successfully!",
      unfreezeSuccess: "🔓 Wallet unfrozen successfully!",
      resolveSuccess: "✅ Risk alert resolved successfully.",
      titleCritical: "Critical Alert",
      titleSecurity: "Security Alert",
      userNotFound: "User account information not found.",
      disabledReactivateHint: "Disabled accounts must be reactivated from the Users page.",
      errUpdateUserStatus: "System error while updating account status.",
      errUpdateWalletStatus: "System error while updating wallet status.",
      errResolveAlert: "System error while processing alert.",
      userLabel: "User:",
      confirmRequest: "Confirm Request",
      cancel: "Cancel",
      agree: "Agree",
      errorAlertTitle: "Error Alert",
      notificationTitle: "Notification",
      close: "Close"
    },
    adminUsers: {
      title: "User Management",
      usersCount: "{count} users",
      searchPlaceholder: "Search by name, email, ID...",
      details: "Details",
      noUsers: "No users found",
      fallbackUser: "User",
      fallbackUserLower: "user",
      notUpdated: "Not updated",
      notProvided: "Not provided",
      bank: "Bank",
      walletFrozen: "❄️ Frozen",
      walletActive: "🟢 Active",
      filters: { all: "All", verified: "KYC Verified", pending: "Pending Review", none: "KYC Not Provided" },
      headers: { id: "ID", name: "Name", email: "Email", kyc: "KYC", status: "Status", balance: "Balance", actions: "Actions" },
      kyc: { verified: "KYC Verified", pending: "Pending Review", rejected: "KYC Rejected", none: "KYC Not Provided" },
      status: { active: "Active", locked: "Locked", disabled: "Disabled" },
      userModalTitle: "User: {name}",
      tabInfo: "Info",
      tabIdDocs: "ID Docs",
      tabTransactions: "Transactions",
      infoLabels: { id: "ID", email: "Email", phone: "Phone", kyc: "KYC", accountStatus: "Account Status", walletStatus: "Wallet Status", balance: "Balance", joined: "Joined" },
      noIdDocs: "This user has not submitted ID documents or has not requested KYC verification.",
      cccdLabels: { nationalId: "National ID", fullName: "Full Name", dob: "Date of Birth", gender: "Gender", address: "Permanent Address" },
      uploadedDocuments: "Uploaded Documents",
      imgFront: "ID Card – Front",
      imgBack: "ID Card – Back",
      imgSelfie: "Selfie",
      referenceImages: "Reference Images (Chip-Enabled ID Card)",
      txTotal: "Total Txns",
      txSuccessful: "Successful",
      txPending: "Pending",
      noTxHistory: "No transaction history",
      txStatusSuccess: "Successful",
      txStatusPending: "Pending",
      txStatusFailed: "Failed",
      btnApproveKyc: "✅ Approve KYC",
      btnRejectKyc: "❌ Reject KYC",
      btnLockAccount: "Lock Account",
      btnUnlockAccount: "Unlock Account",
      btnReactivate: "✅ Reactivate Account",
      btnUnfreezeWallet: "❄️ Unfreeze Wallet",
      btnFreezeWallet: "🔒 Freeze Wallet",
      btnClose: "Close",
      rejectModalTitle: "Reject KYC Application",
      rejectModalDesc: "Please enter a reason for rejecting the verification application to notify the user:",
      rejectPlaceholder: "Enter rejection reason...",
      btnConfirm: "Confirm",
      btnCancel: "Cancel",
      defaultRejectReason: "Identity documents are unclear or information does not match.",
      alertRejectReasonRequired: "Please provide a reason for rejecting KYC.",
      alertApproveSuccess: "✅ KYC approved for {name}!",
      alertRejectSuccess: "❌ KYC rejected for {name}.",
      alertLockSuccess: "🔒 Account locked successfully.",
      alertUnlockSuccess: "✅ Account unlocked successfully.",
      alertReactivateSuccess: "✅ Account reactivated successfully.",
      alertFreezeSuccess: "❄️ Wallet frozen successfully.",
      alertUnfreezeSuccess: "✅ Wallet unfrozen successfully.",
      confirmLock: "Lock account for {name}?\n\nThe user will not be able to sign in or use wallet features until unlocked.",
      confirmUnlock: "Unlock account for {name}?\n\nThe user will regain access to their account and wallet.",
      confirmReactivate: "Reactivate account for {name}?",
      confirmFreeze: "Freeze wallet for {name}?\n\nAll deposits, withdrawals, and transfers will be blocked until unfrozen.",
      confirmUnfreeze: "Unfreeze wallet for {name}?\n\nThe user will be able to use wallet features again.",
      errorApprove: "System error while approving KYC.",
      errorReject: "System error while rejecting KYC.",
      errorLock: "System error while changing account status.",
      errorReactivate: "System error while reactivating account.",
      errorFreeze: "System error while changing wallet status."
    },
    adminTransactions: {
      userFallback: "User",
      toastLoadFailed: "Failed to load transaction list",
      toastApproveSuccess: "✅ Transaction {id} approved successfully",
      toastApproveFailed: "Failed to approve transaction",
      toastServerError: "Server error",
      toastRejectSuccess: "❌ Transaction {id} rejected",
      toastRejectFailed: "Failed to reject transaction",
      headerTitle: "📋 Transaction Management",
      headerSubtitle: "Approve and monitor deposit, withdrawal, and transfer requests from users",
      statTotalLabel: "Total Transactions",
      statTotalDesc: "System history",
      statPendingLabel: "Pending Requests",
      statPendingDesc: "Requires immediate action",
      statCompletedLabel: "Completed",
      statCompletedDesc: "Successful transactions",
      statFailedLabel: "Failed",
      statFailedDesc: "Failed transactions",
      searchPlaceholder: "Search by Transaction ID, user name, or content...",
      statusAll: "All",
      statusPending: "Pending",
      statusSuccess: "Successful",
      statusFailed: "Failed",
      typeAll: "All Types",
      typeDeposit: "Deposit",
      typeWithdrawTransfer: "Withdraw/Transfer",
      notePrefix: "Note: ",
      pillSuccess: "Successful",
      pillPending: "Pending",
      pillFailed: "Failed",
      pillPendingApproval: "Pending Approval",
      btnApprove: "Approve",
      btnReject: "Reject",
      noMatchingTx: "No matching transactions found",
      modalTitle: "Transaction Request Details",
      rowTransactionId: "Transaction ID",
      rowTransactionType: "Transaction Type",
      valueDeposit: "Deposit",
      valueWithdrawTransfer: "Withdraw/Transfer",
      rowCategory: "Category",
      rowInitiatedBy: "Initiated By",
      rowCreatedAt: "Created At",
      rowNoteDescription: "Note / Description"
    },
    adminInvestment: {
      pageTitle: "📈 Savings & Investment Management",
      pageSubtitle: "Monitor all accumulated savings accounts and investment balances across users",
      activeSavingsPrincipal: "Active Savings Principal",
      activeSavingsPrincipalDesc: "Total principal across {count} active accounts",
      accruedInterestActive: "Accrued Interest (Active)",
      accruedInterestActiveDesc: "Estimated cumulative interest accrued to date",
      totalSettledPrincipal: "Total Settled Principal",
      totalSettledPrincipalDesc: "Principal from {count} successfully withdrawn accounts",
      totalInterestPaidOut: "Total Interest Paid Out",
      totalInterestPaidOutDesc: "Total interest actually disbursed to main wallets",
      filterAll: "All",
      filterActive: "Active",
      filterSettled: "Settled",
      searchPlaceholder: "Search by email, phone, or ID...",
      loadingRecords: "Loading investment records...",
      noRecordsFound: "No matching savings records found",
      colId: "ID",
      colCustomer: "CUSTOMER",
      colPrincipal: "PRINCIPAL",
      colTerm: "TERM",
      colInterestRate: "INTEREST RATE",
      colOpenDate: "OPEN DATE",
      colAccruedInterest: "ACCRUED INTEREST",
      colStatus: "STATUS",
      flexible: "Flexible",
      termMonths: "{count} Months",
      maturity: "Maturity: {date}",
      notAvailable: "N/A",
      statusSettled: "SETTLED",
      statusActive: "ACTIVE",
      unknown: "Unknown",
      noEmail: "No Email"
    },
    adminServices: {
      pageTitle: "Service Management",
      pageSubtitle: "Vouchers, transaction fees, and spending categories",
      addVoucher: "Add Voucher",
      tabVoucher: "Voucher",
      tabFee: "Transaction Fees",
      tabCategory: "Categories",
      colCode: "Code",
      colDiscount: "Discount",
      colType: "Type",
      colExpiry: "Expiry",
      colTitle: "Title",
      colStatus: "Status",
      statusActive: "Active",
      statusInactive: "Inactive",
      noVouchers: "No vouchers yet. Click \"+ Add Voucher\" to get started.",
      addFee: "Add Fee",
      noFees: "No fee rules yet. Click \"+ Add Fee\" to create one.",
      transactionTypePrefix: "Transaction Type: ",
      editBtn: "Edit",
      deleteBtn: "Delete",
      newCategoryPlaceholder: "New category name...",
      addCategoryBtn: "Add",
      editVoucherTitle: "Edit Voucher",
      addVoucherTitle: "Add Voucher",
      labelCode: "Code",
      placeholderCode: "e.g. BLACKRED50",
      labelDisplayTitle: "Display Title",
      placeholderTitle: "e.g. Save 50K on transfer fees",
      labelShortDesc: "Short Description",
      placeholderDesc: "e.g. Applicable for transactions from 500K",
      labelDiscountType: "Discount Type",
      optionFixed: "Fixed (₫)",
      optionPercentage: "Percentage (%)",
      labelValue: "Value",
      placeholderValuePercent: "e.g. 10",
      placeholderValueFixed: "e.g. 50000",
      labelMinTransaction: "Min. Transaction (₫)",
      placeholderMinTransaction: "0",
      labelQuantity: "Quantity",
      placeholderQuantity: "e.g. 100",
      labelExpiryDate: "Expiry Date",
      labelStatus: "Status",
      labelTag: "Tag (marketing, used to filter the Offers page)",
      hotEnabled: "HOT (enabled)",
      markAsHot: "Mark as HOT",
      hotBadgeHint: "Shows a 🔥 badge on the card",
      cancelBtn: "Cancel",
      updateBtn: "Update",
      addNewBtn: "Add New",
      editFeeTitle: "Edit Transaction Fee",
      addFeeTitle: "Add Transaction Fee",
      labelTransactionType: "Transaction Type",
      labelFixedFee: "Fixed Fee (VND)",
      placeholderFixedFee: "e.g. 5000",
      saveChangesBtn: "Save Changes",
      failedToAddCategory: "Failed to add category",
      failedToDeleteCategory: "Failed to delete category",
      feeValueInvalid: "Fee value must be a number >= 0 (VND).",
      failedToSaveFee: "Failed to save fee.",
      serverErrorSavingFee: "Server error while saving fee.",
      deleteFeeConfirm: "Delete this fee rule?",
      errorDeletingFee: "Error deleting fee.",
      enterCodeAndTitle: "Please enter a Code and Title!",
      discountValuePositive: "Discount value must be > 0",
      quantityPositive: "Quantity must be > 0",
      selectExpiryDate: "Please select an expiry date",
      failedToSaveVoucher: "Failed to save voucher",
      serverErrorSavingVoucher: "Server error while saving voucher",
      deleteVoucherConfirm: "Delete this voucher?",
      errorDeletingVoucher: "Error deleting voucher",
      errorUpdatingStatus: "Error updating status",
      txLabel: { TRANSFER: "Internal Transfer", WITHDRAW: "Bank Withdrawal/Transfer", PAYMENT: "Payment", DEPOSIT: "Top-up" }
    },
    adminSupport: {
      imageSizeError: "Image size must not exceed 5MB.",
      sendError: "Unable to send reply. Please try again.",
      searchPlaceholder: "Search by email or phone number...",
      noConversations: "No support conversations found.",
      imageLabel: "📎 Image",
      noMessagesYet: "No messages yet",
      phoneLabel: "Phone:",
      notAvailable: "N/A",
      attachmentAlt: "Attachment",
      imageSelected: "Image selected",
      replyPlaceholder: "Reply to {name}...",
      emptyTitle: "Customer Support Center",
      emptyDesc: "Select a customer from the list on the left to view the conversation and send a reply."
    }
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(localStorage.getItem("lang") || "vi");

  useEffect(() => {
    localStorage.setItem("lang", lang);
    document.documentElement.lang = lang;
  }, [lang]);

  const value = useMemo(
    () => ({
      lang,
      setLang,
      toggleLang: () => setLang((prev) => (prev === "vi" ? "en" : "vi")),
      t: translations[lang] || translations.vi,
    }),
    [lang]
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used inside LanguageProvider");
  }
  return context;
}
