import { createContext, useContext, useEffect, useMemo, useState } from "react";

const LanguageContext = createContext(null);

export const translations = {
  vi: {
    nav: {
      home: "Trang chủ",
      about: "Giới thiệu",
      offers: "Ưu đãi",
      transfer: "Chuyển tiền",
      contact: "Liên hệ",
      login: "Đăng nhập",
      dashboard: "Dashboard",
      logout: "Đăng xuất",
      profile: "Hồ sơ cá nhân",
      qrDeposit: "Nạp QR Sandbox",
      myQr: "QR Nhận tiền",
      myWallets: "Ví của tôi",
      investment: "Tích lũy & Đầu tư",
      support: "Hỗ trợ trực tuyến",
    },
    index: {
      eyebrow: "SmartWallet Tài chính số",
      heroTitle1: "Xây dựng trải nghiệm",
      heroTitle2: "SmartWallet",
      heroTitle3: "mượt mà cho người dùng hiện đại.",
      heroLead:
        "Quản lý số dư thời gian thực, nạp/rút tiền nhanh chóng, theo dõi chi tiêu qua biểu đồ trực quan và tạo hũ tiết kiệm theo mục tiêu cá nhân.",
      getStarted: "Bắt đầu ngay →",
      ourServices: "Dịch vụ",
      serviceTitle: "Dịch vụ tài chính nổi bật của SmartWallet",
      offerPrefix: "Ưu đãi #",
      offersCount: "ưu đãi",
      offerRunning: "Ưu đãi đang chạy",
      newsEyebrow: "SmartWallet Insights",
      newsTitle: "Tin tức tài chính mới nhất",
      newsDesc:
        "Cập nhật nhanh các thông báo, ưu đãi và xu hướng tài chính số do admin SmartWallet đăng tải.",
      viewAll: "Xem tất cả",
      marketUpdate: "Cập nhật thị trường",
      readPost: "Đọc bài viết",
      finance: "Tài chính",
      justNow: "Vừa xong",
      newText: "Mới",
      featureTitle: "Dịch vụ cao cấp với trải nghiệm mượt mà.",
      closeNews: "Đóng chi tiết tin tức",
    },
    cards: [
      {
        title: "💳 Nạp tiền",
        desc: "Nạp tiền nhanh chóng từ ngân hàng vào ví.",
      },
      {
        title: "💸 Chuyển tiền",
        desc: "Chuyển tiền an toàn và tức thì.",
      },
      {
        title: "🎁 Ưu đãi & Voucher",
        desc: "Ưu đãi độc quyền dành cho người dùng SmartWallet.",
      },
      {
        title: "📈 Đầu tư",
        desc: "Đầu tư thông minh với các gói tài chính linh hoạt.",
      },
    ],
    offers: [
      {
        title: "Giảm 20% phí giao dịch",
        description: "Áp dụng cho chuyển tiền và thanh toán QR.",
      },
      {
        title: "Voucher nạp ví",
        description: "Nhận ưu đãi khi nạp ví lần đầu.",
      },
      {
        title: "Hoàn tiền QR",
        description: "Hoàn tiền khi thanh toán QR tại cửa hàng.",
      },
    ],
    news: [
      {
        title: "SmartWallet cập nhật bảo mật giao dịch thời gian thực",
        tag: "Tài chính số",
        time: "Vừa xong",
        content:
          "Theo dõi biến động số dư, cảnh báo giao dịch và bảo vệ ví điện tử với trải nghiệm nhanh, rõ ràng hơn cho người dùng SmartWallet.",
      },
      {
        title: "Ưu đãi phí chuyển tiền cho người dùng mới",
        tag: "Ưu đãi",
        time: "Hôm nay",
        content:
          "Các chương trình voucher mới giúp người dùng tiết kiệm chi phí khi chuyển tiền, nạp ví và thanh toán QR.",
      },
      {
        title: "Quản lý chi tiêu cá nhân bằng biểu đồ thông minh",
        tag: "Quản lý tiền",
        time: "1 ngày trước",
        content:
          "SmartWallet giúp phân loại dòng tiền, thống kê thu chi và hỗ trợ người dùng đưa ra quyết định tài chính tốt hơn.",
      },
    ],
    features: [
      {
        title: "Bảo mật tài khoản",
        desc: "Bảo vệ ví bằng KYC, PIN giao dịch và cảnh báo tức thì.",
      },
      {
        title: "Thanh toán linh hoạt",
        desc: "Nạp, rút, chuyển tiền và thanh toán ngân hàng trong cùng một hệ sinh thái.",
      },
      {
        title: "Quản lý tài chính",
        desc: "Theo dõi thu chi, ưu đãi và biến động số dư rõ ràng hơn.",
      },
    ],
    dashboard: {
      availableBalance: "Số dư khả dụng",
      active: "ĐANG HOẠT ĐỘNG",
      frozen: "BỊ ĐÓNG BĂNG",
      deposit: "Nạp tiền",
      withdraw: "Rút tiền",
      transfer: "Chuyển tiền",
      qrCode: "Mã QR",
      linkedBanks: "Ngân hàng liên kết",
      accountsLinked: "tài khoản đã liên kết",
      addBank: "Thêm ngân hàng",
      transactionHistory: "Lịch sử giao dịch",
      searchTransactions: "Tìm kiếm giao dịch...",
      all: "Tất cả",
      receive: "Nhận tiền",
      send: "Chuyển tiền",
      success: "Thành công",
      pending: "Đang xử lý",
      failed: "Thất bại",
      noTransactions: "Không tìm thấy giao dịch nào",
    },
    wallets: {
      freezeConfirmTitle: "Đóng băng ví của bạn?",
      freezeConfirmText: "Hành động này không thể tự hoàn tác. Đóng băng ví sẽ ngay lập tức vô hiệu hóa tất cả nạp, rút và chuyển tiền. Chỉ có đội ngũ hỗ trợ mới có thể mở khóa ví cho bạn.",
      freezeButton: "Đóng băng ngay",
      cancel: "Hủy",
      walletFrozenBanner: "Ví đã bị đóng băng. Tất cả giao dịch đã bị vô hiệu hóa. Vui lòng liên hệ hỗ trợ để phục hồi quyền truy cập.",
      contactSupport: "Liên hệ Hỗ trợ",
      pinSetupTitle: "Thiết lập mã PIN giao dịch",
      pinSetupText: "Vui lòng chọn mã PIN gồm 4 chữ số để sử dụng khi chuyển tiền hoặc rút tiền.",
      enterNewPin: "Nhập mã PIN mới (4 số)",
      confirmNewPin: "Xác nhận mã PIN mới",
      confirmAndSet: "Xác nhận & Thiết lập",
      enterPinToConfirm: "Nhập mã PIN giao dịch để xác nhận",
      depositTitle: "Nạp tiền vào ví",
      depositSuccess: "Nạp tiền thành công! Số dư của bạn đã được cập nhật.",
      minimumDeposit: "Số tiền nạp tối thiểu là 1.000₫!",
      selectLinkedBank: "Chọn tài khoản ngân hàng đã liên kết:",
      amountToDeposit: "Số tiền muốn nạp:",
      note: "Lời nhắn:",
      depositViaBank: "Nạp qua Ngân hàng liên kết",
      depositViaPayos: "Nạp qua QR Ngân hàng (PayOS)",
      processing: "Đang xử lý...",
      withdrawTitle: "Rút tiền về ngân hàng",
      withdrawMin: "Số tiền rút tối thiểu là 10.000₫!",
      selectBankWithdraw: "Chọn tài khoản ngân hàng nhận tiền:",
      transferTitle: "Chuyển tiền",
      transferMethod: "Phương thức chuyển tiền:",
      viaEmailPhone: "Qua Email / Số điện thoại",
      viaBankSandbox: "Qua Ngân hàng Sandbox",
      recipientEmail: "Email/SĐT người nhận:",
      amountToTransfer: "Số tiền chuyển:",
      selectCategory: "Chọn danh mục chuyển tiền:",
      applyVoucher: "Áp dụng mã giảm giá:",
      placeholderVoucher: "Nhập mã voucher...",
      apply: "Áp dụng",
      appliedVoucher: "Đã áp dụng mã",
      saveText: "tiết kiệm được",
      chooseVoucher: "Chọn Voucher có sẵn",
      linkedBanksList: "Danh sách ngân hàng đã liên kết",
      unlink: "Hủy liên kết",
      bankName: "Tên ngân hàng",
      accountNumber: "Số tài khoản",
      accountHolder: "Tên chủ tài khoản",
      linkNewBank: "Liên kết ngân hàng mới",
      selectBank: "Chọn ngân hàng",
      submit: "Xác nhận",
      depositDesc: "Nạp tiền vào tài khoản SmartWallet của bạn",
      selectDepositMethod: "Chọn phương thức nạp tiền",
      depositFromLinkedBankTitle: "🏦 Nạp tiền từ Ngân hàng liên kết",
      noLinkedBanksDesc: "Vui lòng liên kết tài khoản ngân hàng để thực hiện nạp tiền",
      linkBankNow: "Liên kết ngân hàng ngay",
      confirmDeposit: "Xác nhận nạp tiền",
      bankTransferDepositTitle: "📱 Nạp tiền chuyển khoản ngân hàng",
      bankTransferDepositDesc: "Vui lòng quét mã QR hoặc chuyển khoản thủ công tới tài khoản quản trị viên bên dưới",
      checkingStatus: "Hệ thống đang tự động kiểm tra trạng thái giao dịch...",
      openPayosPage: "🔗 Mở trang thanh toán PayOS (Chế độ thử nghiệm)",
      iHaveTransferred: "Tôi đã chuyển tiền",
      withdrawDesc: "Rút tiền về tài khoản ngân hàng của bạn",
      withdrawAmountLabel: "Số tiền rút (₫)",
      confirmWithdrawBtn: "Xác nhận rút tiền",
      withdrawPinDesc: "Vui lòng nhập mã PIN giao dịch gồm 4 chữ số để xác nhận rút tiền.",
      confirmWithdrawalTitle: "Xác nhận rút tiền",
      transferDesc: "Chuyển tiền nhanh chóng và an toàn",
      uploadQrTitle: "Tải lên ảnh mã QR ngân hàng (tùy chọn)",
      clickToUploadQr: "Nhấp để tải lên ảnh QR",
      orEnterManually: "hoặc nhập thủ công",
      recipientAccount: "Số tài khoản người nhận *",
      recipientOwner: "Tên chủ tài khoản (tùy chọn)",
      enterAccountPlaceholder: "Nhập số tài khoản",
      enterOwnerPlaceholder: "Tên đầy đủ người nhận",
      promoRewardTitle: "Mã giảm giá & Phần thưởng",
      browsePromoCodes: "Xem các mã giảm giá có sẵn",
      removePromo: "Gỡ bỏ",
      appliedPromo: "Đã áp dụng",
      discountPromo: "Giảm giá",
      enterVoucherAmountAlert: "Vui lòng nhập số tiền giao dịch để áp dụng mã giảm giá!",
      confirmTransferBtn: "Xác nhận chuyển tiền",
      confirmTransferDiscountedBtn: "Xác nhận chuyển tiền (Đã giảm giá)",
      selectPromoTitle: "Chọn mã giảm giá",
      minTxnAmount: "Giao dịch tối thiểu",
      expDate: "HSD",
      linkLimitReachedTitle: "Đã đạt giới hạn liên kết",
      linkLimitReachedDesc: "Bạn đã liên kết tối đa 3 ngân hàng. Vui lòng hủy liên kết một ngân hàng trước khi thêm mới.",
      linkedBanksProgress: "Ngân hàng đã liên kết",
      onlyOneSlotRemaining: "⚠️ Chỉ còn lại 1 lượt liên kết!",
      bankAccountsLinkedToWallet: "Tài khoản ngân hàng đã liên kết với ví của bạn:",
      addNewBankLink: "+ Thêm liên kết ngân hàng mới",
      txDetailTitle: "Chi tiết giao dịch",
      txDetailAmount: "Số tiền",
      txDetailId: "Mã giao dịch",
      txDetailType: "Loại giao dịch",
      txDetailCategory: "Danh mục",
      txDetailSender: "Người gửi",
      txDetailRecipient: "Người nhận",
      txDetailDate: "Ngày & Giờ",
      txDetailNote: "Lời nhắn",
      cannotBeUndone: "Hành động này không thể tự hoàn tác",
      depositAmount: "Số tiền nạp",
      noLinkedBanks: "Chưa liên kết ngân hàng",
      bankNameLabel: "Ngân hàng",
      accountNumberLabel: "Số tài khoản",
      accountHolderLabel: "Chủ tài khoản",
      amountLabel: "Số tiền",
      transferNoteLabel: "Nội dung chuyển khoản",
      copyBtn: "Sao chép",
      copiedToast: "Đã sao chép",
      enterPinTransferDesc: "Vui lòng nhập mã PIN giao dịch gồm 4 chữ số để xác nhận chuyển tiền.",
      smartwalletTransferInfo: "Chuyển tiền trực tiếp đến tài khoản SmartWallet khác bằng số điện thoại hoặc email đã đăng ký.",
      bankTransferInfo: "Tải lên ảnh mã QR ngân hàng hoặc nhập thủ công thông tin tài khoản người nhận.",
      changeImage: "Thay đổi ảnh",
      banksCountLabel: "ngân hàng",
      removeBtn: "Gỡ",
      linkedCountLabel: "đã liên kết",
      noLinkedBanksDescWithdraw: "Vui lòng thêm tài khoản ngân hàng để thực hiện nạp/rút tiền dễ dàng.",
      kycVerifiedStatus: "Đã xác thực danh tính ✓",
      kycPendingStatus: "Đang chờ duyệt KYC ⏳",
      kycUnverifiedStatus: "Chưa xác thực danh tính ⚠️",
      scanningQr: "Đang quét mã QR...",
      qrTransferPayment: "Chuyển tiền qua mã QR",
      qrScanSuccess: "Quét QR thành công! Đã điền thông tin người nhận.",
      depositViaBankDesc: "Nạp tiền tức thì từ ngân hàng liên kết của bạn",
      depositViaPayosDesc: "Tạo mã QR động cho số tiền cần nạp",
      mbBankAdmin: "Ngân hàng Quân đội MB",
      bankLabel: "Ngân hàng",
      enterPhoneEmailPlaceholder: "Nhập số điện thoại hoặc email",
    },
    kyc: {
      title: "Xác thực danh tính (KYC)",
      subtitle: "Xác thực danh tính để nâng hạn mức giao dịch và mở khóa tất cả tính năng.",
      verifiedTitle: "Danh tính đã được xác thực",
      verifiedDesc: "Hạn mức giao dịch của bạn đã được nâng lên mức tối đa.",
      verifiedInfo: "Thông tin cá nhân đã xác thực",
      fullName: "Họ và tên",
      nationalId: "Số CCCD/CMND",
      dob: "Ngày sinh",
      gender: "Giới tính",
      address: "Địa chỉ thường trú",
      documentsTitle: "Giấy tờ tùy thân & Ảnh chân dung",
      idFront: "Mặt trước CCCD",
      idBack: "Mặt sau CCCD",
      selfie: "Ảnh selfie chân dung",
      noImage: "Chưa có ảnh",
      requestUpdate: "Yêu cầu cập nhật thông tin KYC",
      underReviewTitle: "Hồ sơ đang được xem xét",
      underReviewDesc: "Chúng tôi đã nhận được hồ sơ xác thực của bạn và đang tiến hành kiểm tra. Vui lòng chờ phản hồi trong vòng 1-3 ngày làm việc.",
      rejectedTitle: "Hồ sơ xác thực bị từ chối",
      rejectedDesc: "Vui lòng kiểm tra lại thông tin và ảnh tải lên để gửi lại hồ sơ.",
      personalInfo: "Thông tin cá nhân",
      uploadDocuments: "Tải lên giấy tờ",
      underReviewStep: "Đang xem xét",
      next: "Tiếp tục",
      back: "Quay lại",
      submitKyc: "Gửi hồ sơ xác thực",
      uploadPrompt: "Chọn ảnh",
      alertNote: "Ảnh chụp cần rõ nét, không bị mờ hoặc bị che khuất. Định dạng chấp nhận: JPG / PNG / WEBP / GIF, tối đa 5 MB.",
    },
    myQr: {
      title: "Mã QR nhận tiền của bạn",
      subtitle: "Dùng mã QR này để người khác quét và chuyển tiền vào ví SmartWallet của bạn.",
      userId: "Mã người dùng",
      email: "Email nhận",
      downloadQr: "Tải ảnh QR",
      copyQr: "Copy QR",
      copied: "Đã copy",
      transfer: "Chuyển tiền",
    },
    qrSandbox: {
      title: "SmartWallet Sandbox QR nạp tiền",
      subtitle: "Tạo mã QR giả lập để nạp tiền từ ngân hàng vào ví SmartWallet.",
      createTitle: "Tạo QR nạp tiền",
      amountLabel: "Số tiền nạp",
      amountPlaceholder: "VD: 100000",
      createBtn: "Tạo mã QR",
      creating: "Đang tạo QR...",
      demoFlowTitle: "Quy trình Demo Sandbox:",
      step1: "1. Nhập số tiền nạp.",
      step2: "2. Nhấp xác nhận giả lập quét QR để chuyển tiền từ ngân hàng vào ví.",
      paymentTitle: "Thanh toán QR",
      noQrText: "Chưa có QR. Hãy nhập số tiền và tạo QR.",
      amount: "Số tiền",
      reference: "Mã tham chiếu",
      status: "Trạng thái",
      simulateScanBtn: "Giả lập đã quét QR và thanh toán",
      simulating: "Đang giả lập thanh toán...",
      successTitle: "Nạp tiền thành công",
      failedTitle: "Giao dịch thất bại",
      newBalance: "Số dư mới",
    },
  },

  en: {
    nav: {
      home: "Home",
      about: "About",
      offers: "Offers",
      transfer: "Transfer",
      contact: "Contact",
      login: "Login",
      dashboard: "Dashboard",
      logout: "Logout",
      profile: "Profile",
      qrDeposit: "QR Deposit",
      myQr: "My QR",
      myWallets: "My Wallets",
      investment: "Investments & Savings",
      support: "Live Support",
    },
    index: {
      eyebrow: "SmartWallet Digital Finance",
      heroTitle1: "We Build Smooth",
      heroTitle2: "SmartWallet",
      heroTitle3: "Experiences For Modern Users.",
      heroLead:
        "Manage real-time balances, deposit and withdraw quickly, track spending with visual charts, and create personal savings goals.",
      getStarted: "Get Started →",
      ourServices: "Our Services",
      serviceTitle: "Featured Financial Services From SmartWallet",
      offerPrefix: "Offer #",
      offersCount: "offers",
      offerRunning: "Active offer",
      newsEyebrow: "SmartWallet Insights",
      newsTitle: "Latest Financial News",
      newsDesc:
        "Quick updates on announcements, offers, and digital finance trends published by SmartWallet admins.",
      viewAll: "View all",
      marketUpdate: "Market Update",
      readPost: "Read article",
      finance: "Finance",
      justNow: "Just now",
      newText: "New",
      featureTitle: "Premium Services With Smooth Micro Animation.",
      closeNews: "Close news detail",
    },
    cards: [
      {
        title: "💳 Deposit",
        desc: "Quickly top up your wallet from your bank account.",
      },
      {
        title: "💸 Transfer",
        desc: "Send money safely and instantly.",
      },
      {
        title: "🎁 Offers & Vouchers",
        desc: "Exclusive deals for SmartWallet users.",
      },
      {
        title: "📈 Investment",
        desc: "Smart investing with flexible financial packages.",
      },
    ],
    offers: [
      {
        title: "20% transaction fee discount",
        description: "Applies to transfers and QR payments.",
      },
      {
        title: "Wallet top-up voucher",
        description: "Get a special offer on your first wallet top-up.",
      },
      {
        title: "QR cashback",
        description: "Get cashback when paying by QR at supported stores.",
      },
    ],
    news: [
      {
        title: "SmartWallet updates real-time transaction security",
        tag: "Digital Finance",
        time: "Just now",
        content:
          "Track balance changes, receive transaction alerts, and protect your e-wallet with a faster and clearer SmartWallet experience.",
      },
      {
        title: "Transfer fee offers for new users",
        tag: "Offers",
        time: "Today",
        content:
          "New voucher campaigns help users save money when transferring, topping up, and paying by QR.",
      },
      {
        title: "Manage personal spending with smart charts",
        tag: "Money Management",
        time: "1 day ago",
        content:
          "SmartWallet helps categorize cash flow, summarize income and expenses, and support better financial decisions.",
      },
    ],
    features: [
      {
        title: "Account Security",
        desc: "Protect your wallet with KYC, transaction PIN, and instant alerts.",
      },
      {
        title: "Flexible Payments",
        desc: "Deposit, withdraw, transfer, and make bank payments in one ecosystem.",
      },
      {
        title: "Financial Management",
        desc: "Track income, expenses, offers, and balance changes more clearly.",
      },
    ],
    dashboard: {
      availableBalance: "Available Balance",
      active: "ACTIVE",
      frozen: "FROZEN",
      deposit: "Deposit",
      withdraw: "Withdraw",
      transfer: "Transfer",
      qrCode: "QR Code",
      linkedBanks: "Linked Banks",
      accountsLinked: "accounts linked",
      addBank: "Add Bank",
      transactionHistory: "Transaction History",
      searchTransactions: "Search transactions...",
      all: "All",
      receive: "Receive",
      send: "Send",
      success: "Success",
      pending: "Processing",
      failed: "Failed",
      noTransactions: "No transactions found",
    },
    wallets: {
      freezeConfirmTitle: "Freeze Your Wallet?",
      freezeConfirmText: "This action cannot be undone by you. Freezing your wallet will immediately disable all deposits, withdrawals, and transfers. Only our support team can unfreeze it.",
      freezeButton: "Freeze Now",
      cancel: "Cancel",
      walletFrozenBanner: "Wallet Frozen. All transactions are disabled. To restore access, please contact support.",
      contactSupport: "Contact Support",
      pinSetupTitle: "Set Up Transaction PIN",
      pinSetupText: "Please choose a 4-digit PIN to use when transferring or withdrawing funds.",
      enterNewPin: "Enter new PIN (4 digits)",
      confirmNewPin: "Confirm new PIN",
      confirmAndSet: "Confirm & Set Up",
      enterPinToConfirm: "Enter transaction PIN to confirm",
      depositTitle: "Deposit to Wallet",
      depositSuccess: "Deposit successful! Your balance has been updated.",
      minimumDeposit: "Minimum deposit is 1,000₫!",
      selectLinkedBank: "Select a linked bank account:",
      amountToDeposit: "Amount to deposit:",
      note: "Note:",
      depositViaBank: "Deposit via Linked Bank",
      depositViaPayos: "Deposit via QR Bank (PayOS)",
      processing: "Processing...",
      withdrawTitle: "Withdraw to Bank",
      withdrawMin: "Minimum withdrawal is 10,000₫!",
      selectBankWithdraw: "Select destination bank account:",
      transferTitle: "Transfer Money",
      transferMethod: "Transfer Method:",
      viaEmailPhone: "Via Email / Phone",
      viaBankSandbox: "Via Bank Sandbox",
      recipientEmail: "Recipient Email/Phone:",
      amountToTransfer: "Amount to transfer:",
      selectCategory: "Select transaction category:",
      applyVoucher: "Apply Discount Code:",
      placeholderVoucher: "Enter voucher code...",
      apply: "Apply",
      appliedVoucher: "Applied voucher",
      saveText: "saved",
      chooseVoucher: "Choose Available Voucher",
      linkedBanksList: "Linked Bank Accounts",
      unlink: "Unlink",
      bankName: "Bank Name",
      accountNumber: "Account Number",
      accountHolder: "Account Holder",
      linkNewBank: "Link New Bank",
      selectBank: "Select Bank",
      submit: "Submit",
      depositDesc: "Add funds to your SmartWallet account",
      selectDepositMethod: "Select deposit method",
      depositFromLinkedBankTitle: "🏦 Deposit from Linked Bank",
      noLinkedBanksDesc: "Please link a bank account to make a deposit",
      linkBankNow: "Link a Bank Now",
      confirmDeposit: "Confirm Deposit",
      bankTransferDepositTitle: "📱 Bank Transfer Deposit",
      bankTransferDepositDesc: "Please scan the QR code or manually transfer to the admin account below",
      checkingStatus: "System is automatically checking transaction status...",
      openPayosPage: "🔗 Open PayOS Payment Page (Test Mode)",
      iHaveTransferred: "I Have Transferred",
      withdrawDesc: "Withdraw to your bank account",
      withdrawAmountLabel: "Withdrawal amount (₫)",
      confirmWithdrawBtn: "Confirm Withdrawal",
      withdrawPinDesc: "Please enter your 4-digit transaction PIN to confirm the withdrawal.",
      confirmWithdrawalTitle: "Confirm Withdrawal",
      transferDesc: "Fast and secure money transfer",
      uploadQrTitle: "Upload bank QR code image (optional)",
      clickToUploadQr: "Click to upload QR image",
      orEnterManually: "or enter manually",
      recipientAccount: "Recipient's account number *",
      recipientOwner: "Account holder name (optional)",
      enterAccountPlaceholder: "Enter account number",
      enterOwnerPlaceholder: "Full name of recipient",
      promoRewardTitle: "Promo Codes & Rewards",
      browsePromoCodes: "Browse available codes",
      removePromo: "Remove",
      appliedPromo: "Applied",
      discountPromo: "Discount",
      enterVoucherAmountAlert: "Please enter an amount before applying a promo code!",
      confirmTransferBtn: "Confirm Transfer",
      confirmTransferDiscountedBtn: "Confirm Transfer (Discounted)",
      selectPromoTitle: "Select Promo Code",
      minTxnAmount: "Min Txn",
      expDate: "Exp",
      linkLimitReachedTitle: "Link Limit Reached",
      linkLimitReachedDesc: "You have reached the maximum of 3 linked banks. Please remove an existing bank before adding a new one.",
      linkedBanksProgress: "Linked banks",
      onlyOneSlotRemaining: "⚠️ Only 1 slot remaining!",
      bankAccountsLinkedToWallet: "Bank accounts linked to your wallet:",
      addNewBankLink: "+ Add New Bank Link",
      txDetailTitle: "Transaction Details",
      txDetailAmount: "Amount",
      txDetailId: "Transaction ID",
      txDetailType: "Type",
      txDetailCategory: "Category",
      txDetailSender: "Sender",
      txDetailRecipient: "Recipient",
      txDetailDate: "Date & Time",
      txDetailNote: "Note",
      cannotBeUndone: "This action cannot be undone",
      depositAmount: "Deposit amount",
      noLinkedBanks: "No linked bank accounts",
      bankNameLabel: "Bank",
      accountNumberLabel: "Account Number",
      accountHolderLabel: "Account Holder",
      amountLabel: "Amount",
      transferNoteLabel: "Transfer Note",
      copyBtn: "Copy",
      copiedToast: "Copied",
      enterPinTransferDesc: "Please enter your 4-digit transaction PIN to confirm the transfer.",
      smartwalletTransferInfo: "Transfer directly to a SmartWallet account using a registered phone number or email.",
      bankTransferInfo: "Upload a bank QR image or manually enter the recipient's bank and account number.",
      changeImage: "Change Image",
      banksCountLabel: "banks",
      removeBtn: "Remove",
      linkedCountLabel: "linked",
      noLinkedBanksDescWithdraw: "Please add a bank account to easily deposit and withdraw funds.",
      kycVerifiedStatus: "Account verified ✓",
      kycPendingStatus: "KYC pending review ⏳",
      kycUnverifiedStatus: "KYC not verified ⚠️",
      scanningQr: "Reading QR Code...",
      qrTransferPayment: "QR transfer payment",
      qrScanSuccess: "QR Code parsed successfully! Recipient info filled.",
      depositViaBankDesc: "Instant deposit from your linked bank account",
      depositViaPayosDesc: "Generate a QR code for the deposit amount",
      mbBankAdmin: "MB Bank (Military Bank)",
      bankLabel: "Bank",
      enterPhoneEmailPlaceholder: "Enter phone number or email",
    },
    kyc: {
      title: "Identity Verification (KYC)",
      subtitle: "Verify your identity to increase transaction limits and unlock all features.",
      verifiedTitle: "Identity Verified",
      verifiedDesc: "Your transaction limits have been upgraded to the maximum level.",
      verifiedInfo: "Verified Personal Information",
      fullName: "Full Name",
      nationalId: "National ID",
      dob: "Date of Birth",
      gender: "Gender",
      address: "Permanent Address",
      documentsTitle: "ID Documents & Portrait",
      idFront: "ID Card – Front",
      idBack: "ID Card – Back",
      selfie: "Selfie Portrait",
      noImage: "No image",
      requestUpdate: "Request KYC Information Update",
      underReviewTitle: "Application Under Review",
      underReviewDesc: "We have received your KYC application and it is currently under review. Please wait for 1-3 business days.",
      rejectedTitle: "KYC Application Rejected",
      rejectedDesc: "Please review your uploaded information and documents and submit again.",
      personalInfo: "Personal Info",
      uploadDocuments: "Upload Documents",
      underReviewStep: "Under Review",
      next: "Next",
      back: "Back",
      submitKyc: "Submit for Verification",
      uploadPrompt: "Choose image",
      alertNote: "Photos must be clear, unblurred, and unobstructed. Accepted formats: JPG / PNG / WEBP / GIF, max 5 MB.",
    },
    myQr: {
      title: "Your QR Code",
      subtitle: "Show this QR code to others to receive transfers directly into your SmartWallet.",
      userId: "User ID",
      email: "Receiver Email",
      downloadQr: "Download QR",
      copyQr: "Copy QR",
      copied: "Copied",
      transfer: "Transfer",
    },
    qrSandbox: {
      title: "SmartWallet Sandbox QR Deposit",
      subtitle: "Create a mockup QR code to deposit simulated funds into your SmartWallet.",
      createTitle: "Create QR Deposit",
      amountLabel: "Deposit Amount",
      amountPlaceholder: "e.g. 100000",
      createBtn: "Create QR Deposit",
      creating: "Creating QR...",
      demoFlowTitle: "Sandbox Demo Flow:",
      step1: "1. Enter the deposit amount.",
      step2: "2. Click simulation button to mimic bank payment and credit your wallet.",
      paymentTitle: "QR Payment",
      noQrText: "No QR generated. Enter an amount and click generate.",
      amount: "Amount",
      reference: "Reference",
      status: "Status",
      simulateScanBtn: "Simulate scan & payment",
      simulating: "Simulating payment...",
      successTitle: "Deposit Successful",
      failedTitle: "Transaction Failed",
      newBalance: "New Balance",
    },
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(localStorage.getItem("lang") || "vi");

  useEffect(() => {
    localStorage.setItem("lang", lang);
    document.documentElement.lang = lang;
  }, [lang]);

  const value = useMemo(
    () => ({
      lang,
      setLang,
      toggleLang: () => setLang((prev) => (prev === "vi" ? "en" : "vi")),
      t: translations[lang] || translations.vi,
    }),
    [lang]
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used inside LanguageProvider");
  }
  return context;
}
